/**
 * اسم الشهادة — the classified professional-certification master list
 * delivered 2026-09-21, extracted verbatim (by script —
 * `tools/data/extract-reference-lists.py`) from
 * `docs/inputs/certification-master-list.xlsx`.
 *
 * Two of its columns are what make Evaluation-Matrix criteria #7 and #8
 * computable — both were «No source field exists» (`EVAL-GAP-04`/`EVAL-GAP-05`)
 * until this file arrived:
 *
 * - `relevant` — the workbook's «Financial Sector Relevance». Criterion #7
 *   («مجال الشهادة المهنية», max 5%) pays 0.05 when ANY entered certificate is
 *   relevant. 138 of 228 are.
 * - `isGlobal` — the workbook's «Geographic Recognition» («Global» vs
 *   «Saudi / Local»). Criterion #8 («مصدر الشهادة», max 4%) pays 0.04 when ANY
 *   entered certificate is global, else 0.02 when any is local.
 *   157 of 228 are global.
 *
 * Both are best-of (MAX) across the applicant's certificate entries, per the
 * matrix's «Certificate Multi-Entry Scoring Policy» — «Do No Harm»: an added
 * entry can only help, never hurt.
 *
 * ⚠️ English-only at source. `labelAr` mirrors `labelEn` rather than inventing
 * an Arabic name for a certification trademarked in English.
 *
 * The workbook's `Credential Type`, `Official Certification URL`, `Topic` and
 * `Other Specialty` columns are deliberately NOT carried: no approved field
 * consumes them, and no criterion scores them.
 */

export interface ProfessionalCertificationOption {
  readonly value: string;
  readonly labelAr: string;
  readonly labelEn: string;
  /** «Financial Sector Relevance» — Evaluation Matrix criterion #7. */
  readonly relevant: boolean;
  /** «Geographic Recognition» = Global — Evaluation Matrix criterion #8. */
  readonly isGlobal: boolean;
}

export const PROFESSIONAL_CERTIFICATION_OPTIONS: readonly ProfessionalCertificationOption[] = [
  {
    value: 'CERT-0001',
    labelAr: 'Saudi Board Certification (Saudi Commission for Health Specialties)',
    labelEn: 'Saudi Board Certification (Saudi Commission for Health Specialties)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0002',
    labelAr:
      'Health Practitioner Professional Classification and Registration (Saudi Commission for Health Specialties)',
    labelEn:
      'Health Practitioner Professional Classification and Registration (Saudi Commission for Health Specialties)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0003',
    labelAr: 'SOCPA Fellowship Certificate',
    labelEn: 'SOCPA Fellowship Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0004',
    labelAr: 'SOCPA VAT Specialist Certificate',
    labelEn: 'SOCPA VAT Specialist Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0005',
    labelAr: 'SOCPA Accounting Technician Certificate',
    labelEn: 'SOCPA Accounting Technician Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0006',
    labelAr: 'SOCPA Professional Certification in Public Sector Accounting Standards',
    labelEn: 'SOCPA Professional Certification in Public Sector Accounting Standards',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0007',
    labelAr: 'SOCPA Financial Fraud Examiner Certification',
    labelEn: 'SOCPA Financial Fraud Examiner Certification',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0008',
    labelAr: 'SOCPA International Financial Reporting Standards (IFRS) Certificate',
    labelEn: 'SOCPA International Financial Reporting Standards (IFRS) Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0009',
    labelAr: 'SOCPA Government Accounting Training Track Certificate',
    labelEn: 'SOCPA Government Accounting Training Track Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0010',
    labelAr: 'SOCPA Government Auditing Training Track Certificate',
    labelEn: 'SOCPA Government Auditing Training Track Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0011',
    labelAr: 'Accounting and Auditing Practice License (SOCPA)',
    labelEn: 'Accounting and Auditing Practice License (SOCPA)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0012',
    labelAr:
      'CMA Qualification Examination: International Introduction to Securities and Investment (CME-1A)',
    labelEn:
      'CMA Qualification Examination: International Introduction to Securities and Investment (CME-1A)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0013',
    labelAr:
      'CMA Qualification Examination: General Saudi Capital Market Rules and Regulations (CME-1B)',
    labelEn:
      'CMA Qualification Examination: General Saudi Capital Market Rules and Regulations (CME-1B)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0014',
    labelAr: 'CMA Qualification Examination: Global Financial Compliance (CME-2A)',
    labelEn: 'CMA Qualification Examination: Global Financial Compliance (CME-2A)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0015',
    labelAr:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Compliance, Anti-Money Laundering and Combating the Financing of Terrorism (CME-2B)',
    labelEn:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Compliance, Anti-Money Laundering and Combating the Financing of Terrorism (CME-2B)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0016',
    labelAr: 'CMA Qualification Examination: Securities (CME-3A)',
    labelEn: 'CMA Qualification Examination: Securities (CME-3A)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0017',
    labelAr:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Brokers (CME-3B)',
    labelEn:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Brokers (CME-3B)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0018',
    labelAr:
      'CMA Qualification Examination: International Certificate in Wealth and Investment Management (CME-4A)',
    labelEn:
      'CMA Qualification Examination: International Certificate in Wealth and Investment Management (CME-4A)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0019',
    labelAr:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Asset Managers (CME-4B)',
    labelEn:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Asset Managers (CME-4B)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0020',
    labelAr: 'CMA Qualification Examination: Corporate Finance Technical Foundations (CME-5A)',
    labelEn: 'CMA Qualification Examination: Corporate Finance Technical Foundations (CME-5A)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0021',
    labelAr:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Corporate Finance (CME-5B)',
    labelEn:
      'CMA Qualification Examination: Saudi Capital Market Rules and Regulations - Corporate Finance (CME-5B)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0022',
    labelAr: 'Insurance Fundamentals Certificate Examination (IFCE)',
    labelEn: 'Insurance Fundamentals Certificate Examination (IFCE)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0023',
    labelAr: 'Credit Advisor Certification (SAMA-mandated)',
    labelEn: 'Credit Advisor Certification (SAMA-mandated)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0024',
    labelAr: 'Compliance Foundations Professional Certificate (Financial Academy)',
    labelEn: 'Compliance Foundations Professional Certificate (Financial Academy)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0025',
    labelAr: 'Professional Certification in Compliance for the Financing Companies Sector',
    labelEn: 'Professional Certification in Compliance for the Financing Companies Sector',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0026',
    labelAr: 'Taqeem Fellowship Certificate in Real Estate Valuation',
    labelEn: 'Taqeem Fellowship Certificate in Real Estate Valuation',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0027',
    labelAr: 'Taqeem Fellowship Certificate in Business Valuation',
    labelEn: 'Taqeem Fellowship Certificate in Business Valuation',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0028',
    labelAr: 'Taqeem Fellowship Certificate in Machinery and Equipment Valuation',
    labelEn: 'Taqeem Fellowship Certificate in Machinery and Equipment Valuation',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0029',
    labelAr: "Taqeem Professional Certificate - Inspector (Mu'ayin)",
    labelEn: "Taqeem Professional Certificate - Inspector (Mu'ayin)",
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0030',
    labelAr: 'Accredited Valuer License (Taqeem)',
    labelEn: 'Accredited Valuer License (Taqeem)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0031',
    labelAr:
      'Professional Accreditation of Engineers - Associate / Professional / Consultant Classification (Saudi Council of Engineers)',
    labelEn:
      'Professional Accreditation of Engineers - Associate / Professional / Consultant Classification (Saudi Council of Engineers)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0032',
    labelAr: 'Real Estate Brokerage (FAL) License (Real Estate General Authority)',
    labelEn: 'Real Estate Brokerage (FAL) License (Real Estate General Authority)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0033',
    labelAr: 'Lawyer Practice License (Ministry of Justice)',
    labelEn: 'Lawyer Practice License (Ministry of Justice)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0034',
    labelAr: 'Professional License for Teachers (Education and Training Evaluation Commission)',
    labelEn: 'Professional License for Teachers (Education and Training Evaluation Commission)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0035',
    labelAr: 'Commercial Pilot License (General Authority of Civil Aviation)',
    labelEn: 'Commercial Pilot License (General Authority of Civil Aviation)',
    relevant: false,
    isGlobal: false,
  },
  {
    value: 'CERT-0036',
    labelAr: 'Project Management Professional (PMP)',
    labelEn: 'Project Management Professional (PMP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0037',
    labelAr: 'Certified Associate in Project Management (CAPM)',
    labelEn: 'Certified Associate in Project Management (CAPM)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0038',
    labelAr: 'Program Management Professional (PgMP)',
    labelEn: 'Program Management Professional (PgMP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0039',
    labelAr: 'Portfolio Management Professional (PfMP)',
    labelEn: 'Portfolio Management Professional (PfMP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0040',
    labelAr: 'PMI Agile Certified Practitioner (PMI-ACP)',
    labelEn: 'PMI Agile Certified Practitioner (PMI-ACP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0041',
    labelAr: 'PMI Risk Management Professional (PMI-RMP)',
    labelEn: 'PMI Risk Management Professional (PMI-RMP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0042',
    labelAr: 'PMI Scheduling Professional (PMI-SP)',
    labelEn: 'PMI Scheduling Professional (PMI-SP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0043',
    labelAr: 'PMI Professional in Business Analysis (PMI-PBA)',
    labelEn: 'PMI Professional in Business Analysis (PMI-PBA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0044',
    labelAr: 'PMI Construction Professional (PMI-CP)',
    labelEn: 'PMI Construction Professional (PMI-CP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0045',
    labelAr: 'PMI PMO Certified Professional (PMI-PMOCP)',
    labelEn: 'PMI PMO Certified Professional (PMI-PMOCP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0046',
    labelAr: 'Professional Scrum Master I (PSM I)',
    labelEn: 'Professional Scrum Master I (PSM I)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0047',
    labelAr: 'Professional Scrum Product Owner I (PSPO I)',
    labelEn: 'Professional Scrum Product Owner I (PSPO I)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0048',
    labelAr: 'Certified ScrumMaster (CSM)',
    labelEn: 'Certified ScrumMaster (CSM)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0049',
    labelAr: 'Certified Scrum Product Owner (CSPO)',
    labelEn: 'Certified Scrum Product Owner (CSPO)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0050',
    labelAr: 'Entry Certificate in Business Analysis (ECBA)',
    labelEn: 'Entry Certificate in Business Analysis (ECBA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0051',
    labelAr: 'Certification of Capability in Business Analysis (CCBA)',
    labelEn: 'Certification of Capability in Business Analysis (CCBA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0052',
    labelAr: 'Certified Business Analysis Professional (CBAP)',
    labelEn: 'Certified Business Analysis Professional (CBAP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0053',
    labelAr: 'TOGAF Enterprise Architecture Certification',
    labelEn: 'TOGAF Enterprise Architecture Certification',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0054',
    labelAr: 'ITIL 4 Foundation',
    labelEn: 'ITIL 4 Foundation',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0055',
    labelAr: 'ASQ Certified Six Sigma Green Belt (CSSGB)',
    labelEn: 'ASQ Certified Six Sigma Green Belt (CSSGB)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0056',
    labelAr: 'ASQ Certified Six Sigma Black Belt (CSSBB)',
    labelEn: 'ASQ Certified Six Sigma Black Belt (CSSBB)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0057',
    labelAr: 'ASQ Certified Quality Engineer (CQE)',
    labelEn: 'ASQ Certified Quality Engineer (CQE)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0058',
    labelAr: 'ASQ Certified Quality Auditor (CQA)',
    labelEn: 'ASQ Certified Quality Auditor (CQA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0059',
    labelAr: 'ASQ Certified Manager of Quality/Organizational Excellence (CMQ/OE)',
    labelEn: 'ASQ Certified Manager of Quality/Organizational Excellence (CMQ/OE)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0060',
    labelAr: 'Certified Supply Chain Professional (CSCP)',
    labelEn: 'Certified Supply Chain Professional (CSCP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0061',
    labelAr: 'Certified in Planning and Inventory Management (CPIM)',
    labelEn: 'Certified in Planning and Inventory Management (CPIM)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0062',
    labelAr: 'Certified in Logistics, Transportation and Distribution (CLTD)',
    labelEn: 'Certified in Logistics, Transportation and Distribution (CLTD)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0063',
    labelAr: 'SHRM Certified Professional (SHRM-CP)',
    labelEn: 'SHRM Certified Professional (SHRM-CP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0064',
    labelAr: 'SHRM Senior Certified Professional (SHRM-SCP)',
    labelEn: 'SHRM Senior Certified Professional (SHRM-SCP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0065',
    labelAr: 'Professional in Human Resources (PHR)',
    labelEn: 'Professional in Human Resources (PHR)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0066',
    labelAr: 'Senior Professional in Human Resources (SPHR)',
    labelEn: 'Senior Professional in Human Resources (SPHR)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0067',
    labelAr: 'Global Professional in Human Resources (GPHR)',
    labelEn: 'Global Professional in Human Resources (GPHR)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0068',
    labelAr: 'Certified Professional in Talent Development (CPTD)',
    labelEn: 'Certified Professional in Talent Development (CPTD)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0069',
    labelAr: 'ICF Associate Certified Coach (ACC)',
    labelEn: 'ICF Associate Certified Coach (ACC)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0070',
    labelAr: 'ICF Professional Certified Coach (PCC)',
    labelEn: 'ICF Professional Certified Coach (PCC)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0071',
    labelAr: 'ICF Master Certified Coach (MCC)',
    labelEn: 'ICF Master Certified Coach (MCC)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0072',
    labelAr: 'Nielsen Norman Group UX Certification',
    labelEn: 'Nielsen Norman Group UX Certification',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0073',
    labelAr: 'IAAP Certified Professional in Accessibility Core Competencies (CPACC)',
    labelEn: 'IAAP Certified Professional in Accessibility Core Competencies (CPACC)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0074',
    labelAr: 'IAAP Web Accessibility Specialist (WAS)',
    labelEn: 'IAAP Web Accessibility Specialist (WAS)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0075',
    labelAr: 'Chartered Financial Analyst (CFA) Charterholder',
    labelEn: 'Chartered Financial Analyst (CFA) Charterholder',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0076',
    labelAr: 'Certified Public Accountant (CPA)',
    labelEn: 'Certified Public Accountant (CPA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0077',
    labelAr: 'Certified Management Accountant (CMA)',
    labelEn: 'Certified Management Accountant (CMA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0078',
    labelAr: 'Certified Internal Auditor (CIA)',
    labelEn: 'Certified Internal Auditor (CIA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0079',
    labelAr: 'ACCA Qualification (Association of Chartered Certified Accountants)',
    labelEn: 'ACCA Qualification (Association of Chartered Certified Accountants)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0080',
    labelAr: 'ICAEW Chartered Accountancy Qualification (ACA)',
    labelEn: 'ICAEW Chartered Accountancy Qualification (ACA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0081',
    labelAr: 'CPA Australia Certified Practising Accountant',
    labelEn: 'CPA Australia Certified Practising Accountant',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0082',
    labelAr: 'Certified Financial Planner (CFP)',
    labelEn: 'Certified Financial Planner (CFP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0083',
    labelAr: 'Financial Risk Manager (FRM)',
    labelEn: 'Financial Risk Manager (FRM)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0084',
    labelAr: 'Energy Risk Professional (ERP)',
    labelEn: 'Energy Risk Professional (ERP)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0085',
    labelAr: 'Sustainability and Climate Risk (SCR) Certificate',
    labelEn: 'Sustainability and Climate Risk (SCR) Certificate',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0086',
    labelAr: 'Chartered Alternative Investment Analyst (CAIA)',
    labelEn: 'Chartered Alternative Investment Analyst (CAIA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0087',
    labelAr: 'Professional Risk Manager (PRM)',
    labelEn: 'Professional Risk Manager (PRM)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0088',
    labelAr: 'Chartered Market Technician (CMT)',
    labelEn: 'Chartered Market Technician (CMT)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0089',
    labelAr: 'Certified Fraud Examiner (CFE)',
    labelEn: 'Certified Fraud Examiner (CFE)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0090',
    labelAr: 'Certified Anti-Money Laundering Specialist (CAMS)',
    labelEn: 'Certified Anti-Money Laundering Specialist (CAMS)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0091',
    labelAr: 'Series 7 - General Securities Representative Qualification Examination',
    labelEn: 'Series 7 - General Securities Representative Qualification Examination',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0092',
    labelAr: 'Series 24 - General Securities Principal Qualification Examination',
    labelEn: 'Series 24 - General Securities Principal Qualification Examination',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0093',
    labelAr: 'Chartered Property Casualty Underwriter (CPCU)',
    labelEn: 'Chartered Property Casualty Underwriter (CPCU)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0094',
    labelAr: 'Associate of the Society of Actuaries (ASA)',
    labelEn: 'Associate of the Society of Actuaries (ASA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0095',
    labelAr: 'Fellow of the Society of Actuaries (FSA)',
    labelEn: 'Fellow of the Society of Actuaries (FSA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0096',
    labelAr: 'Chartered Insurance Institute Qualifications (ACII / FCII)',
    labelEn: 'Chartered Insurance Institute Qualifications (ACII / FCII)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0097',
    labelAr: 'Certified Information Systems Auditor (CISA)',
    labelEn: 'Certified Information Systems Auditor (CISA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0098',
    labelAr: 'Certified Information Security Manager (CISM)',
    labelEn: 'Certified Information Security Manager (CISM)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0099',
    labelAr: 'Certified in Risk and Information Systems Control (CRISC)',
    labelEn: 'Certified in Risk and Information Systems Control (CRISC)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0100',
    labelAr: 'Certified in the Governance of Enterprise IT (CGEIT)',
    labelEn: 'Certified in the Governance of Enterprise IT (CGEIT)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0101',
    labelAr: 'Certified Data Privacy Solutions Engineer (CDPSE)',
    labelEn: 'Certified Data Privacy Solutions Engineer (CDPSE)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0102',
    labelAr: 'Certified Information Systems Security Professional (CISSP)',
    labelEn: 'Certified Information Systems Security Professional (CISSP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0103',
    labelAr: 'Certified Cloud Security Professional (CCSP)',
    labelEn: 'Certified Cloud Security Professional (CCSP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0104',
    labelAr: 'Systems Security Certified Practitioner (SSCP)',
    labelEn: 'Systems Security Certified Practitioner (SSCP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0105',
    labelAr: 'Certified Secure Software Lifecycle Professional (CSSLP)',
    labelEn: 'Certified Secure Software Lifecycle Professional (CSSLP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0106',
    labelAr: 'Certified in Governance, Risk and Compliance (CGRC)',
    labelEn: 'Certified in Governance, Risk and Compliance (CGRC)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0107',
    labelAr: 'Certified in Cybersecurity (CC)',
    labelEn: 'Certified in Cybersecurity (CC)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0108',
    labelAr: 'CompTIA A+',
    labelEn: 'CompTIA A+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0109',
    labelAr: 'CompTIA Network+',
    labelEn: 'CompTIA Network+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0110',
    labelAr: 'CompTIA Security+',
    labelEn: 'CompTIA Security+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0111',
    labelAr: 'CompTIA Cloud+',
    labelEn: 'CompTIA Cloud+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0112',
    labelAr: 'CompTIA Linux+',
    labelEn: 'CompTIA Linux+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0113',
    labelAr: 'CompTIA Server+',
    labelEn: 'CompTIA Server+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0114',
    labelAr: 'CompTIA Project+',
    labelEn: 'CompTIA Project+',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0115',
    labelAr: 'CompTIA Data+',
    labelEn: 'CompTIA Data+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0116',
    labelAr: 'CompTIA Cybersecurity Analyst (CySA+)',
    labelEn: 'CompTIA Cybersecurity Analyst (CySA+)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0117',
    labelAr: 'CompTIA PenTest+',
    labelEn: 'CompTIA PenTest+',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0118',
    labelAr: 'Certified Ethical Hacker (CEH)',
    labelEn: 'Certified Ethical Hacker (CEH)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0119',
    labelAr: 'Offensive Security Certified Professional (OSCP)',
    labelEn: 'Offensive Security Certified Professional (OSCP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0120',
    labelAr: 'GIAC Security Essentials (GSEC)',
    labelEn: 'GIAC Security Essentials (GSEC)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0121',
    labelAr: 'GIAC Certified Incident Handler (GCIH)',
    labelEn: 'GIAC Certified Incident Handler (GCIH)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0122',
    labelAr: 'GIAC Penetration Tester (GPEN)',
    labelEn: 'GIAC Penetration Tester (GPEN)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0123',
    labelAr: 'GIAC Certified Forensic Analyst (GCFA)',
    labelEn: 'GIAC Certified Forensic Analyst (GCFA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0124',
    labelAr: 'Certified Information Privacy Professional/Europe (CIPP/E)',
    labelEn: 'Certified Information Privacy Professional/Europe (CIPP/E)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0125',
    labelAr: 'Certified Information Privacy Professional/United States (CIPP/US)',
    labelEn: 'Certified Information Privacy Professional/United States (CIPP/US)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0126',
    labelAr: 'Certified Information Privacy Manager (CIPM)',
    labelEn: 'Certified Information Privacy Manager (CIPM)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0127',
    labelAr: 'Certified Information Privacy Technologist (CIPT)',
    labelEn: 'Certified Information Privacy Technologist (CIPT)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0128',
    labelAr: 'Artificial Intelligence Governance Professional (AIGP)',
    labelEn: 'Artificial Intelligence Governance Professional (AIGP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0129',
    labelAr: 'AWS Certified Cloud Practitioner',
    labelEn: 'AWS Certified Cloud Practitioner',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0130',
    labelAr: 'AWS Certified Solutions Architect - Associate',
    labelEn: 'AWS Certified Solutions Architect - Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0131',
    labelAr: 'AWS Certified Solutions Architect - Professional',
    labelEn: 'AWS Certified Solutions Architect - Professional',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0132',
    labelAr: 'AWS Certified Developer - Associate',
    labelEn: 'AWS Certified Developer - Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0133',
    labelAr: 'AWS Certified DevOps Engineer - Professional',
    labelEn: 'AWS Certified DevOps Engineer - Professional',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0134',
    labelAr: 'AWS Certified Security - Specialty',
    labelEn: 'AWS Certified Security - Specialty',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0135',
    labelAr: 'Microsoft Certified: Azure Fundamentals',
    labelEn: 'Microsoft Certified: Azure Fundamentals',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0136',
    labelAr: 'Microsoft Certified: Azure Administrator Associate',
    labelEn: 'Microsoft Certified: Azure Administrator Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0137',
    labelAr: 'Microsoft Certified: Azure Solutions Architect Expert',
    labelEn: 'Microsoft Certified: Azure Solutions Architect Expert',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0138',
    labelAr: 'Microsoft Certified: Azure Developer Associate',
    labelEn: 'Microsoft Certified: Azure Developer Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0139',
    labelAr: 'Microsoft Certified: Azure Security Engineer Associate',
    labelEn: 'Microsoft Certified: Azure Security Engineer Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0140',
    labelAr: 'Microsoft Certified: Azure AI Fundamentals',
    labelEn: 'Microsoft Certified: Azure AI Fundamentals',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0141',
    labelAr: 'Microsoft Certified: Azure Data Fundamentals',
    labelEn: 'Microsoft Certified: Azure Data Fundamentals',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0142',
    labelAr: 'Microsoft Certified: Security, Compliance, and Identity Fundamentals',
    labelEn: 'Microsoft Certified: Security, Compliance, and Identity Fundamentals',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0143',
    labelAr: 'Microsoft Certified: Power BI Data Analyst Associate',
    labelEn: 'Microsoft Certified: Power BI Data Analyst Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0144',
    labelAr: 'Microsoft 365 Fundamentals',
    labelEn: 'Microsoft 365 Fundamentals',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0145',
    labelAr: 'Google Cloud Certified - Cloud Digital Leader',
    labelEn: 'Google Cloud Certified - Cloud Digital Leader',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0146',
    labelAr: 'Google Cloud Certified - Associate Cloud Engineer',
    labelEn: 'Google Cloud Certified - Associate Cloud Engineer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0147',
    labelAr: 'Google Cloud Certified - Professional Cloud Architect',
    labelEn: 'Google Cloud Certified - Professional Cloud Architect',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0148',
    labelAr: 'Google Cloud Certified - Professional Data Engineer',
    labelEn: 'Google Cloud Certified - Professional Data Engineer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0149',
    labelAr: 'Google Cloud Certified - Professional Cloud Developer',
    labelEn: 'Google Cloud Certified - Professional Cloud Developer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0150',
    labelAr: 'Google Cloud Certified - Professional Cloud Security Engineer',
    labelEn: 'Google Cloud Certified - Professional Cloud Security Engineer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0151',
    labelAr: 'Google Cloud Certified - Professional Machine Learning Engineer',
    labelEn: 'Google Cloud Certified - Professional Machine Learning Engineer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0152',
    labelAr: 'Google Cloud Certified - Professional Cloud DevOps Engineer',
    labelEn: 'Google Cloud Certified - Professional Cloud DevOps Engineer',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0153',
    labelAr: 'Cisco Certified Network Associate (CCNA)',
    labelEn: 'Cisco Certified Network Associate (CCNA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0154',
    labelAr: 'Certified Kubernetes Administrator (CKA)',
    labelEn: 'Certified Kubernetes Administrator (CKA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0155',
    labelAr: 'Certified Kubernetes Application Developer (CKAD)',
    labelEn: 'Certified Kubernetes Application Developer (CKAD)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0156',
    labelAr: 'Certified Kubernetes Security Specialist (CKS)',
    labelEn: 'Certified Kubernetes Security Specialist (CKS)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0157',
    labelAr: 'HashiCorp Certified: Terraform Associate',
    labelEn: 'HashiCorp Certified: Terraform Associate',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0158',
    labelAr: 'Red Hat Certified System Administrator (RHCSA)',
    labelEn: 'Red Hat Certified System Administrator (RHCSA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0159',
    labelAr: 'Linux Professional Institute Certification Level 1 (LPIC-1)',
    labelEn: 'Linux Professional Institute Certification Level 1 (LPIC-1)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0160',
    labelAr: 'Salesforce Certified Administrator',
    labelEn: 'Salesforce Certified Administrator',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0161',
    labelAr: 'United States Medical Licensing Examination (USMLE)',
    labelEn: 'United States Medical Licensing Examination (USMLE)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0162',
    labelAr: 'ECFMG Certification',
    labelEn: 'ECFMG Certification',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0163',
    labelAr: 'American Board of Medical Specialties (ABMS) Board Certification',
    labelEn: 'American Board of Medical Specialties (ABMS) Board Certification',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0164',
    labelAr: 'National Council Licensure Examination for Registered Nurses (NCLEX-RN)',
    labelEn: 'National Council Licensure Examination for Registered Nurses (NCLEX-RN)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0165',
    labelAr: 'North American Pharmacist Licensure Examination (NAPLEX)',
    labelEn: 'North American Pharmacist Licensure Examination (NAPLEX)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0166',
    labelAr: 'Medical Registration with a Licence to Practise (UK General Medical Council)',
    labelEn: 'Medical Registration with a Licence to Practise (UK General Medical Council)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0167',
    labelAr: 'ASCP Board of Certification (BOC) Credentials',
    labelEn: 'ASCP Board of Certification (BOC) Credentials',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0168',
    labelAr: 'Professional Engineer (PE) License',
    labelEn: 'Professional Engineer (PE) License',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0169',
    labelAr: 'Fundamentals of Engineering (FE) Examination / Engineer Intern Certification',
    labelEn: 'Fundamentals of Engineering (FE) Examination / Engineer Intern Certification',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0170',
    labelAr: 'Chartered Engineer (CEng)',
    labelEn: 'Chartered Engineer (CEng)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0171',
    labelAr: 'Member of the Royal Institution of Chartered Surveyors (MRICS)',
    labelEn: 'Member of the Royal Institution of Chartered Surveyors (MRICS)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0172',
    labelAr: 'LEED Accredited Professional (LEED AP)',
    labelEn: 'LEED Accredited Professional (LEED AP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0173',
    labelAr: 'Certified Safety Professional (CSP)',
    labelEn: 'Certified Safety Professional (CSP)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0174',
    labelAr: 'NEBOSH Qualifications in Occupational Health and Safety',
    labelEn: 'NEBOSH Qualifications in Occupational Health and Safety',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0175',
    labelAr: 'Airline Transport Pilot (ATP) Certificate (FAA)',
    labelEn: 'Airline Transport Pilot (ATP) Certificate (FAA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0176',
    labelAr: 'Certificate in Teaching English to Speakers of Other Languages (CELTA)',
    labelEn: 'Certificate in Teaching English to Speakers of Other Languages (CELTA)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0177',
    labelAr: 'Certified Strength and Conditioning Specialist (CSCS)',
    labelEn: 'Certified Strength and Conditioning Specialist (CSCS)',
    relevant: false,
    isGlobal: true,
  },
  {
    value: 'CERT-0178',
    labelAr: 'PRINCE2 Foundation',
    labelEn: 'PRINCE2 Foundation',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0179',
    labelAr: 'PRINCE2 Practitioner',
    labelEn: 'PRINCE2 Practitioner',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0180',
    labelAr: 'Certified Risk Management Specialist (CRMS)',
    labelEn: 'Certified Risk Management Specialist (CRMS)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0181',
    labelAr: 'Certified Credit Specialist (CCS)',
    labelEn: 'Certified Credit Specialist (CCS)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0182',
    labelAr: 'Certified Internal Audit Specialist (CIAS)',
    labelEn: 'Certified Internal Audit Specialist (CIAS)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0183',
    labelAr: 'Certified Anti-Fraud Practitioner (CAFP)',
    labelEn: 'Certified Anti-Fraud Practitioner (CAFP)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0184',
    labelAr: 'Foundation Risk Management Qualification in Financial Services (RMFS)',
    labelEn: 'Foundation Risk Management Qualification in Financial Services (RMFS)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0185',
    labelAr: 'Foreign Exchange Professional Exam (SAMA-mandated)',
    labelEn: 'Foreign Exchange Professional Exam (SAMA-mandated)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0186',
    labelAr: 'Retail Banking Foundations Exam (SAMA-mandated)',
    labelEn: 'Retail Banking Foundations Exam (SAMA-mandated)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0187',
    labelAr: 'Individuals Financing Fundamentals Professional Exam (IFFE)',
    labelEn: 'Individuals Financing Fundamentals Professional Exam (IFFE)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0188',
    labelAr: 'Fundamentals of Islamic Banking Professional Exam',
    labelEn: 'Fundamentals of Islamic Banking Professional Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0189',
    labelAr: 'Professional Exam for Compliance Officer in the Insurance Sector (SAMA-mandated)',
    labelEn: 'Professional Exam for Compliance Officer in the Insurance Sector (SAMA-mandated)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0190',
    labelAr: 'Certified Investor Relations Officer (CIRO) Certificate',
    labelEn: 'Certified Investor Relations Officer (CIRO) Certificate',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0191',
    labelAr: 'CII Award in General Insurance (Non-UK) (W01/W02)',
    labelEn: 'CII Award in General Insurance (Non-UK) (W01/W02)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0192',
    labelAr: 'CII Award in Customer Service in Insurance (Non-UK) (W04)',
    labelEn: 'CII Award in Customer Service in Insurance (Non-UK) (W04)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0193',
    labelAr: 'CII General Insurance Business (IF2)',
    labelEn: 'CII General Insurance Business (IF2)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0194',
    labelAr: 'CII Insurance Business and Finance (M92)',
    labelEn: 'CII Insurance Business and Finance (M92)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0195',
    labelAr: 'CII Insurance Law (M05)',
    labelEn: 'CII Insurance Law (M05)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0196',
    labelAr: 'CII Insurance Broking Practice (M81)',
    labelEn: 'CII Insurance Broking Practice (M81)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0197',
    labelAr: 'CII Claims Practice (M85)',
    labelEn: 'CII Claims Practice (M85)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0198',
    labelAr: 'CII Insurance Underwriting Practice (M80)',
    labelEn: 'CII Insurance Underwriting Practice (M80)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0199',
    labelAr: 'CII Insurance Underwriting (Non-UK) (WUE/WUA)',
    labelEn: 'CII Insurance Underwriting (Non-UK) (WUE/WUA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0200',
    labelAr: 'CII Reinsurance (M97)',
    labelEn: 'CII Reinsurance (M97)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0201',
    labelAr: 'SME Financing Expert Certificate',
    labelEn: 'SME Financing Expert Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0202',
    labelAr: 'SME Financing Specialist Certificate',
    labelEn: 'SME Financing Specialist Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0203',
    labelAr: 'Financial Awareness Expert Certificate',
    labelEn: 'Financial Awareness Expert Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0204',
    labelAr: 'Certified Debt Collection Professional (CDCP)',
    labelEn: 'Certified Debt Collection Professional (CDCP)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0205',
    labelAr: 'Certified Export Credit Finance and Insurance Professional (CEFIP)',
    labelEn: 'Certified Export Credit Finance and Insurance Professional (CEFIP)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0206',
    labelAr: 'Certified Compliance Officer (CCO) Professional Exam',
    labelEn: 'Certified Compliance Officer (CCO) Professional Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0207',
    labelAr: 'Advanced Compliance Professional Certificate',
    labelEn: 'Advanced Compliance Professional Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0208',
    labelAr: 'Professional Exam of Compliance in the Banks Sector',
    labelEn: 'Professional Exam of Compliance in the Banks Sector',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0209',
    labelAr: 'Compliance and Sharia Audit Professional Exam (CSAP)',
    labelEn: 'Compliance and Sharia Audit Professional Exam (CSAP)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0210',
    labelAr: 'Insurance Claims Officer Professional Exam',
    labelEn: 'Insurance Claims Officer Professional Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0211',
    labelAr: 'Insurance Underwriting Officer Professional Exam',
    labelEn: 'Insurance Underwriting Officer Professional Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0212',
    labelAr: 'Insurance Underwriting Assistant Officer Professional Exam',
    labelEn: 'Insurance Underwriting Assistant Officer Professional Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0213',
    labelAr: 'Insurance Sales Officer Certificate',
    labelEn: 'Insurance Sales Officer Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0214',
    labelAr: 'Insurance Claims Processing Officer Certificate',
    labelEn: 'Insurance Claims Processing Officer Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0215',
    labelAr: 'Health Insurance Exam',
    labelEn: 'Health Insurance Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0216',
    labelAr: 'Motor Insurance Exam',
    labelEn: 'Motor Insurance Exam',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0217',
    labelAr: 'Accident Inspector Certificate',
    labelEn: 'Accident Inspector Certificate',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0218',
    labelAr: 'Credit Adviser Professional Certificate - Level 1',
    labelEn: 'Credit Adviser Professional Certificate - Level 1',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0219',
    labelAr: 'Customer Service Employee Professional Certificate - Level 1',
    labelEn: 'Customer Service Employee Professional Certificate - Level 1',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0220',
    labelAr: 'Foreign Exchange Employee Professional Certificate - Level 1',
    labelEn: 'Foreign Exchange Employee Professional Certificate - Level 1',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0221',
    labelAr: 'Tadawul Saudi Exchange Broker (Registered Trader) Professional Exam (BPE)',
    labelEn: 'Tadawul Saudi Exchange Broker (Registered Trader) Professional Exam (BPE)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0222',
    labelAr: 'Tadawul Saudi Exchange Disclosure Professional Exam (IPE)',
    labelEn: 'Tadawul Saudi Exchange Disclosure Professional Exam (IPE)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0223',
    labelAr: 'Certified Anti-Money Laundering Specialist (CMAS)',
    labelEn: 'Certified Anti-Money Laundering Specialist (CMAS)',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0224',
    labelAr: 'General Securities Qualification Examination (CME-1) - Legacy Series',
    labelEn: 'General Securities Qualification Examination (CME-1) - Legacy Series',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0225',
    labelAr:
      'Compliance, Anti-Money Laundering and Counter-Terrorist Financing Certificate Examination (CME-2) - Legacy Series',
    labelEn:
      'Compliance, Anti-Money Laundering and Counter-Terrorist Financing Certificate Examination (CME-2) - Legacy Series',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0226',
    labelAr: 'Securities Brokers Certificate Examination (CME-3) - Legacy Series',
    labelEn: 'Securities Brokers Certificate Examination (CME-3) - Legacy Series',
    relevant: true,
    isGlobal: false,
  },
  {
    value: 'CERT-0227',
    labelAr: 'CII Insurance Claims Handling (Non-UK) (WCE/WCA)',
    labelEn: 'CII Insurance Claims Handling (Non-UK) (WCE/WCA)',
    relevant: true,
    isGlobal: true,
  },
  {
    value: 'CERT-0228',
    labelAr: 'CII Commercial Property and Business Interruption Insurances (M93)',
    labelEn: 'CII Commercial Property and Business Interruption Insurances (M93)',
    relevant: true,
    isGlobal: true,
  },
];
