/**
 * اسم الجامعة — the university list delivered 2026-09-21, extracted verbatim
 * (by script — `tools/data/extract-reference-lists.py`) from the
 * «جميع الجامعات» sheet of `docs/inputs/specializations-and-universities.xlsx`.
 *
 * Closes the Application Form Matrix's Form 2 #4 open item — the field was
 * free text because «the list sits in a file not readable here». 517
 * institutions, inside and outside the Kingdom.
 *
 * The workbook's «الدولة / المدينة» column is deliberately NOT carried: no
 * approved field consumes it, and no criterion scores it.
 *
 * ⚠️ Codes (`uni-NNN`) are positional and stable — this module's own, pending
 * a real `profile.Education.Donor` lookup id.
 */

export interface UniversityOption {
  readonly value: string;
  readonly labelAr: string;
  readonly labelEn: string;
}

export const UNIVERSITY_OPTIONS: readonly UniversityOption[] = [
  { value: 'uni-001', labelAr: 'جامعة الملك سعود', labelEn: 'King Saud University' },
  {
    value: 'uni-002',
    labelAr: 'جامعة الإمام محمد بن سعود الإسلامية',
    labelEn: 'Imam Muhammad ibn Saud Islamic University',
  },
  {
    value: 'uni-003',
    labelAr: 'جامعة الأميرة نورة بنت عبدالرحمن',
    labelEn: 'Princess Nourah bint Abdulrahman University',
  },
  {
    value: 'uni-004',
    labelAr: 'جامعة الأمير سطام بن عبدالعزيز',
    labelEn: 'Prince Sattam bin Abdulaziz University',
  },
  { value: 'uni-005', labelAr: 'جامعة شقراء', labelEn: 'Shaqra University' },
  { value: 'uni-006', labelAr: 'جامعة المجمعة', labelEn: 'Majmaah University' },
  {
    value: 'uni-007',
    labelAr: 'الجامعة السعودية الإلكترونية',
    labelEn: 'Saudi Electronic University',
  },
  { value: 'uni-008', labelAr: 'جامعة الملك عبدالعزيز', labelEn: 'King Abdulaziz University' },
  { value: 'uni-009', labelAr: 'جامعة أم القرى', labelEn: 'Umm Al-Qura University' },
  { value: 'uni-010', labelAr: 'جامعة جدة', labelEn: 'University of Jeddah' },
  { value: 'uni-011', labelAr: 'جامعة الطائف', labelEn: 'Taif University' },
  { value: 'uni-012', labelAr: 'الجامعة الإسلامية', labelEn: 'The Islamic University of Madinah' },
  { value: 'uni-013', labelAr: 'جامعة طيبة', labelEn: 'Taibah University' },
  {
    value: 'uni-014',
    labelAr: 'جامعة الملك فهد للبترول والمعادن',
    labelEn: 'King Fahd University of Petroleum and Minerals',
  },
  {
    value: 'uni-015',
    labelAr: 'جامعة الإمام عبدالرحمن بن فيصل',
    labelEn: 'Imam Abdulrahman Bin Faisal University',
  },
  { value: 'uni-016', labelAr: 'جامعة الملك فيصل', labelEn: 'King Faisal University' },
  { value: 'uni-017', labelAr: 'جامعة الملك خالد', labelEn: 'King Khalid University' },
  { value: 'uni-018', labelAr: 'جامعة الباحة', labelEn: 'Al Baha University' },
  { value: 'uni-019', labelAr: 'جامعة نجران', labelEn: 'Najran University' },
  { value: 'uni-020', labelAr: 'جامعة جازان', labelEn: 'Jazan University' },
  { value: 'uni-021', labelAr: 'جامعة القصيم', labelEn: 'Qassim University' },
  { value: 'uni-022', labelAr: 'جامعة حائل', labelEn: 'University of Hail' },
  { value: 'uni-023', labelAr: 'جامعة الجوف', labelEn: 'Jouf University' },
  { value: 'uni-024', labelAr: 'جامعة تبوك', labelEn: 'University of Tabuk' },
  { value: 'uni-025', labelAr: 'جامعة الحدود الشمالية', labelEn: 'Northern Border University' },
  {
    value: 'uni-026',
    labelAr: 'جامعة الملك سعود بن عبدالعزيز للعلوم الصحية',
    labelEn: 'King Saud bin Abdulaziz University for Health Sciences',
  },
  {
    value: 'uni-027',
    labelAr: 'جامعة الملك عبدالله للعلوم والتقنية (كاوست)',
    labelEn: 'King Abdullah University of Science and Technology (KAUST)',
  },
  { value: 'uni-028', labelAr: 'جامعة الأمير سلطان', labelEn: 'Prince Sultan University' },
  { value: 'uni-029', labelAr: 'جامعة الفيصل', labelEn: 'Alfaisal University' },
  { value: 'uni-030', labelAr: 'جامعة اليمامة', labelEn: 'Yamamah University' },
  { value: 'uni-031', labelAr: 'جامعة دار العلوم', labelEn: 'Dar Al Uloom University' },
  {
    value: 'uni-032',
    labelAr: 'جامعة الأمير محمد بن فهد',
    labelEn: 'Prince Mohammad Bin Fahd University',
  },
  {
    value: 'uni-033',
    labelAr: 'جامعة الأمير فهد بن سلطان',
    labelEn: 'Prince Fahd bin Sultan University',
  },
  { value: 'uni-034', labelAr: 'جامعة عفت', labelEn: 'Effat University' },
  { value: 'uni-035', labelAr: 'جامعة دار الحكمة', labelEn: 'Dar Al-Hekma University' },
  { value: 'uni-036', labelAr: 'جامعة سليمان الراجحي', labelEn: 'Sulaiman AlRajhi University' },
  {
    value: 'uni-037',
    labelAr: 'الجامعة العربية المفتوحة (فرع السعودية)',
    labelEn: 'Arab Open University (Saudi Branch)',
  },
  { value: 'uni-038', labelAr: 'جامعة الفارابي', labelEn: 'Al-Farabi University College' },
  {
    value: 'uni-039',
    labelAr: 'جامعة المدينة العالمية (فرع السعودية)',
    labelEn: 'Al-Madinah International University (Saudi Branch)',
  },
  { value: 'uni-040', labelAr: 'كلية إنجاز', labelEn: 'Enjaz College' },
  { value: 'uni-041', labelAr: 'جامعة حفر الباطن', labelEn: 'University of Hafr Al-Batin' },
  { value: 'uni-042', labelAr: 'جامعة الزلفي', labelEn: 'Al-Zulfi University College' },
  { value: 'uni-043', labelAr: 'جامعة القريات (كلية)', labelEn: 'Qurayyat University (College)' },
  { value: 'uni-044', labelAr: 'جامعة بيشة', labelEn: 'University of Bisha' },
  { value: 'uni-045', labelAr: 'الجامعة العربية المفتوحة', labelEn: 'Arab Open University' },
  {
    value: 'uni-046',
    labelAr: 'جامعة الأعمال والتكنولوجيا',
    labelEn: 'University of Business and Technology',
  },
  {
    value: 'uni-047',
    labelAr: 'جامعة الأمير مقرن بن عبدالعزيز',
    labelEn: 'Prince Muqrin bin Abdulaziz University',
  },
  { value: 'uni-048', labelAr: 'جامعة رياض العلم', labelEn: 'Riyadh Elm University' },
  {
    value: 'uni-049',
    labelAr: 'جامعة الفيصل – كلية الأمير سلطان للإدارة',
    labelEn: 'Alfaisal University – Prince Sultan College of Business',
  },
  {
    value: 'uni-050',
    labelAr: 'كلية ابن رشد للعلوم الإدارية',
    labelEn: 'Ibn Rushd College of Management Sciences',
  },
  { value: 'uni-051', labelAr: 'كلية ابن سينا الأهلية', labelEn: 'Ibn Sina National College' },
  {
    value: 'uni-052',
    labelAr: 'كلية الأمير محمد بن سلمان للإدارة وريادة الأعمال',
    labelEn: 'Prince Mohammed bin Salman College for Business and Entrepreneurship',
  },
  {
    value: 'uni-053',
    labelAr: 'كلية الباحة الأهلية للعلوم',
    labelEn: 'Al Baha National College of Sciences',
  },
  {
    value: 'uni-054',
    labelAr: 'كلية الحقوق والعلوم الإسلامية بالمدينة المنورة',
    labelEn: 'College of Law and Islamic Sciences in Madinah',
  },
  { value: 'uni-055', labelAr: 'كلية الرؤية بالرياض', labelEn: "Al-Ru'ya College in Riyadh" },
  { value: 'uni-056', labelAr: 'كلية الفيحاء الأهلية', labelEn: 'Al-Faihaa National College' },
  {
    value: 'uni-057',
    labelAr: 'كلية جدارة للعلوم الإدارية والإنسانية بحفر الباطن',
    labelEn: 'Jadara College of Administrative and Human Sciences in Hafr Al-Batin',
  },
  {
    value: 'uni-058',
    labelAr: 'كلية جدة العالمية الأهلية',
    labelEn: 'Jeddah International National College',
  },
  {
    value: 'uni-059',
    labelAr: 'كلية كابسارك للسياسات العامة',
    labelEn: 'KAPSARC College of Public Policy',
  },
  { value: 'uni-060', labelAr: 'كلية مكة الأهلية', labelEn: 'Makkah National College' },
  {
    value: 'uni-061',
    labelAr: 'كلية منار الجنوب للعلوم والتقنية',
    labelEn: 'Manar Al-Janoub College of Science and Technology',
  },
  { value: 'uni-062', labelAr: 'كليات الأصالة الأهلية', labelEn: 'Al-Asalah National Colleges' },
  { value: 'uni-063', labelAr: 'كليات بريدة الأهلية', labelEn: 'Buraydah National Colleges' },
  { value: 'uni-064', labelAr: 'كليات الخليج الأهلية', labelEn: 'Al-Khaleej National Colleges' },
  {
    value: 'uni-065',
    labelAr: 'كليات الريان الأهلية بالمدينة المنورة',
    labelEn: 'Al-Rayan National Colleges in Madinah',
  },
  {
    value: 'uni-066',
    labelAr: 'كليات الشرق العربي للدراسات العليا',
    labelEn: 'Arab East Colleges for Graduate Studies',
  },
  { value: 'uni-067', labelAr: 'كليات عنيزة الأهلية', labelEn: 'Unaizah National Colleges' },
  { value: 'uni-068', labelAr: 'جامعة ملبورن', labelEn: 'University of Melbourne' },
  {
    value: 'uni-069',
    labelAr: 'الجامعة الوطنية الأسترالية',
    labelEn: 'The Australian National University',
  },
  {
    value: 'uni-070',
    labelAr: 'جامعة غرب أستراليا',
    labelEn: 'The University of Western Australia',
  },
  { value: 'uni-071', labelAr: 'جامعة كوبنهاغن', labelEn: 'University of Copenhagen' },
  { value: 'uni-072', labelAr: 'جامعة آرهوس', labelEn: 'The University of Aarhus' },
  { value: 'uni-073', labelAr: 'معهد كارولينسكا', labelEn: 'Karolinska Institute' },
  { value: 'uni-074', labelAr: 'جامعة أوبسالا', labelEn: 'University of Uppsala' },
  { value: 'uni-075', labelAr: 'جامعة ستوكهولم', labelEn: 'Stockholm University' },
  { value: 'uni-076', labelAr: 'جامعة هايدلبرغ', labelEn: 'Heidelberg University' },
  { value: 'uni-077', labelAr: 'جامعة بون', labelEn: 'University of Bonn' },
  { value: 'uni-078', labelAr: 'جامعة ميونخ', labelEn: 'University of Munich' },
  { value: 'uni-079', labelAr: 'جامعة أوسلو', labelEn: 'The University of Oslo' },
  { value: 'uni-080', labelAr: 'جامعة طوكيو', labelEn: 'The University of Tokyo' },
  { value: 'uni-081', labelAr: 'جامعة كيوتو', labelEn: 'Kyoto University' },
  { value: 'uni-082', labelAr: 'جامعة ناغويا', labelEn: 'Nagoya University' },
  { value: 'uni-083', labelAr: 'جامعة أوساكا', labelEn: 'Osaka University' },
  { value: 'uni-084', labelAr: 'جامعة هارفارد', labelEn: 'Harvard University' },
  { value: 'uni-085', labelAr: 'جامعة ستانفورد', labelEn: 'Stanford University' },
  {
    value: 'uni-086',
    labelAr: 'معهد ماساتشوستس للتقنية',
    labelEn: 'Massachusetts Institute of Technology',
  },
  {
    value: 'uni-087',
    labelAr: 'جامعة كاليفورنيا - بيركلي',
    labelEn: 'University of California - Berkeley',
  },
  { value: 'uni-088', labelAr: 'جامعة برينستون', labelEn: 'Princeton University' },
  {
    value: 'uni-089',
    labelAr: 'جامعة كولومبيا في مدينة نيويورك',
    labelEn: 'Columbia University in the City of New York',
  },
  { value: 'uni-090', labelAr: 'جامعة شيكاغو', labelEn: 'University of Chicago' },
  { value: 'uni-091', labelAr: 'جامعة ييل', labelEn: 'Yale University' },
  {
    value: 'uni-092',
    labelAr: 'جامعة كاليفورنيا - لوس أنجلوس',
    labelEn: 'University of California - Los Angeles',
  },
  { value: 'uni-093', labelAr: 'جامعة كورنيل', labelEn: 'Cornell University' },
  {
    value: 'uni-094',
    labelAr: 'جامعة واشنطن - سياتل',
    labelEn: 'University of Washington - Seattle',
  },
  { value: 'uni-095', labelAr: 'جامعة بنسلفانيا', labelEn: 'University of Pennsylvania' },
  {
    value: 'uni-096',
    labelAr: 'جامعة كاليفورنيا - سان فرانسيسكو',
    labelEn: 'University of California - San Francisco',
  },
  {
    value: 'uni-097',
    labelAr: 'جامعة ميشيغان - آن أربور',
    labelEn: 'University of Michigan - Ann Arbor',
  },
  {
    value: 'uni-098',
    labelAr: 'جامعة ويسكونسن - ماديسون',
    labelEn: 'University of Wisconsin - Madison',
  },
  { value: 'uni-099', labelAr: 'جامعة نيويورك', labelEn: 'New York University' },
  { value: 'uni-100', labelAr: 'جامعة نورث وسترن', labelEn: 'Northwestern University' },
  {
    value: 'uni-101',
    labelAr: 'جامعة إلينوي في أوربانا شامبين',
    labelEn: 'University of Illinois at Urbana Champaign',
  },
  {
    value: 'uni-102',
    labelAr: 'جامعة مينيسوتا - توين سيتيز',
    labelEn: 'University of Minnesota - Twin Cities',
  },
  { value: 'uni-103', labelAr: 'جامعة ديوك', labelEn: 'Duke University' },
  { value: 'uni-104', labelAr: 'جامعة واشنطن (سانت لويس)', labelEn: 'Washington University' },
  { value: 'uni-105', labelAr: 'جامعة روكفلر', labelEn: 'Rockefeller University' },
  {
    value: 'uni-106',
    labelAr: 'جامعة كولورادو في بولدر',
    labelEn: 'University of Colorado at Boulder',
  },
  {
    value: 'uni-107',
    labelAr: 'جامعة تكساس في أوستن',
    labelEn: 'The University of Texas at Austin',
  },
  {
    value: 'uni-108',
    labelAr: 'جامعة كاليفورنيا - سانتا باربارا',
    labelEn: 'University of California - Santa Barbara',
  },
  {
    value: 'uni-109',
    labelAr: 'جامعة نورث كارولاينا في تشابل هيل',
    labelEn: 'University of North Carolina at Chapel Hill',
  },
  {
    value: 'uni-110',
    labelAr: 'جامعة ميريلاند - كوليدج بارك',
    labelEn: 'University of Maryland - College Park',
  },
  {
    value: 'uni-111',
    labelAr: 'جامعة جنوب كاليفورنيا',
    labelEn: 'University of Southern California',
  },
  {
    value: 'uni-112',
    labelAr: 'جامعة كاليفورنيا - إيرفاين',
    labelEn: 'University of California - Irvine',
  },
  { value: 'uni-113', labelAr: 'جامعة فاندربيلت', labelEn: 'Vanderbilt University' },
  {
    value: 'uni-114',
    labelAr: 'جامعة كاليفورنيا - ديفيس',
    labelEn: 'University of California - Davis',
  },
  {
    value: 'uni-115',
    labelAr: 'جامعة ولاية بنسلفانيا - الحرم الرئيسي',
    labelEn: 'Pennsylvania State University - Main Campus',
  },
  { value: 'uni-116', labelAr: 'جامعة كارنيغي ميلون', labelEn: 'Carnegie Mellon University' },
  {
    value: 'uni-117',
    labelAr: 'جامعة بيردو - الحرم الرئيسي',
    labelEn: 'Purdue University - Main Campus',
  },
  {
    value: 'uni-118',
    labelAr: 'جامعة روتجرز - نيو برونزويك',
    labelEn: 'Rutgers University - New Brunswick',
  },
  {
    value: 'uni-119',
    labelAr: 'جامعة ولاية أوهايو - الحرم الرئيسي',
    labelEn: 'Ohio State University - Main Campus',
  },
  {
    value: 'uni-120',
    labelAr: 'جامعة بيتسبرغ - الحرم الرئيسي',
    labelEn: 'University of Pittsburgh - Main Campus',
  },
  { value: 'uni-121', labelAr: 'جامعة بوسطن', labelEn: 'Boston University' },
  { value: 'uni-122', labelAr: 'جامعة براون', labelEn: 'Brown University' },
  { value: 'uni-123', labelAr: 'جامعة فلوريدا', labelEn: 'University of Florida' },
  { value: 'uni-124', labelAr: 'جامعة رايس', labelEn: 'Rice University' },
  { value: 'uni-125', labelAr: 'جامعة أريزونا', labelEn: 'University of Arizona' },
  {
    value: 'uni-126',
    labelAr: 'جامعة كاليفورنيا - سانتا كروز',
    labelEn: 'University of California - Santa Cruz',
  },
  { value: 'uni-127', labelAr: 'جامعة يوتا', labelEn: 'The University of Utah' },
  { value: 'uni-128', labelAr: 'جامعة ولاية ميشيغان', labelEn: 'Michigan State University' },
  {
    value: 'uni-129',
    labelAr: 'جامعة تكساس إيه آند إم - كوليدج ستيشن',
    labelEn: 'Texas A & M University - College Station',
  },
  {
    value: 'uni-130',
    labelAr: 'جامعة كيس ويسترن ريزيرف',
    labelEn: 'Case Western Reserve University',
  },
  { value: 'uni-131', labelAr: 'جامعة كامبريدج', labelEn: 'University of Cambridge' },
  { value: 'uni-132', labelAr: 'جامعة أكسفورد', labelEn: 'University of Oxford' },
  { value: 'uni-133', labelAr: 'كلية لندن الجامعية', labelEn: 'University College London' },
  { value: 'uni-134', labelAr: 'جامعة مانشستر', labelEn: 'University of Manchester' },
  { value: 'uni-135', labelAr: 'جامعة إدنبرة', labelEn: 'University of Edinburgh' },
  { value: 'uni-136', labelAr: 'كينغز كوليدج لندن', labelEn: "King's College London" },
  { value: 'uni-137', labelAr: 'جامعة بريستول', labelEn: 'University of Bristol' },
  { value: 'uni-138', labelAr: 'جامعة وارويك', labelEn: 'University of Warwick' },
  { value: 'uni-139', labelAr: 'جامعة غنت', labelEn: 'Ghent University' },
  {
    value: 'uni-140',
    labelAr: 'جامعة لوفان الكاثوليكية',
    labelEn: 'Katholieke Universiteit Leuven',
  },
  {
    value: 'uni-141',
    labelAr: 'المعهد الفدرالي السويسري للتقنية في زيورخ',
    labelEn: 'Swiss Federal Institute of Technology Zurich',
  },
  { value: 'uni-142', labelAr: 'جامعة زيورخ', labelEn: 'University of Zurich' },
  { value: 'uni-143', labelAr: 'جامعة جنيف', labelEn: 'University of Geneva' },
  { value: 'uni-144', labelAr: 'جامعة بازل', labelEn: 'University of Basel' },
  {
    value: 'uni-145',
    labelAr: 'جامعة بيير وماري كوري - باريس 6',
    labelEn: 'Pierre and Marie Curie University - Paris 6',
  },
  {
    value: 'uni-146',
    labelAr: 'جامعة باريس الجنوبية (باريس 11)',
    labelEn: 'University of Paris-Sud (Paris 11)',
  },
  {
    value: 'uni-147',
    labelAr: 'المدرسة العليا للأساتذة (إيكول نورمال سوبيريور)',
    labelEn: 'Ecole Normale Superieure',
  },
  { value: 'uni-148', labelAr: 'جامعة ستراسبورغ', labelEn: 'University of Strasbourg' },
  { value: 'uni-149', labelAr: 'جامعة إكس مرسيليا', labelEn: 'Aix Marseille University' },
  { value: 'uni-150', labelAr: 'جامعة هلسنكي', labelEn: 'University of Helsinki' },
  { value: 'uni-151', labelAr: 'جامعة أوترخت', labelEn: 'Utrecht University' },
  { value: 'uni-152', labelAr: 'جامعة غرونينغن', labelEn: 'University of Groningen' },
  { value: 'uni-153', labelAr: 'جامعة ليدن', labelEn: 'Leiden University' },
  { value: 'uni-154', labelAr: 'جامعة أمستردام', labelEn: 'University of Amsterdam' },
  { value: 'uni-155', labelAr: 'جامعة ولاية أريزونا', labelEn: 'ARIZONA STATE UNIVERSITY' },
  {
    value: 'uni-156',
    labelAr: 'معهد جورجيا للتقنية - الحرم الرئيسي',
    labelEn: 'GEORGIA INSTITUTE OF TECHNOLOGY - MAIN CAMPUS',
  },
  {
    value: 'uni-157',
    labelAr: 'جامعة إنديانا - بلومنغتون',
    labelEn: 'INDIANA UNIVERSITY - BLOOMINGTON',
  },
  {
    value: 'uni-158',
    labelAr: 'كلية ديكسون للقانون - جامعة ولاية بنسلفانيا',
    labelEn: 'Penn State Dickson Law-Pennsylvania State University',
  },
  {
    value: 'uni-159',
    labelAr: 'المعهد التقني بجامعة نيويورك',
    labelEn: 'Polytechnic Institute of NYU',
  },
  { value: 'uni-160', labelAr: 'جامعة ولاية سانت كلاود', labelEn: 'St. Cloud State University' },
  { value: 'uni-161', labelAr: 'جامعة تمبل', labelEn: 'Temple University' },
  { value: 'uni-162', labelAr: 'جامعة تكساس إيه آند إم', labelEn: 'TEXAS A & M UNIVERSITY' },
  { value: 'uni-163', labelAr: 'جامعة ولاية أوهايو', labelEn: 'The Ohio State University' },
  { value: 'uni-164', labelAr: 'جامعة توليدو', labelEn: 'The University of Toledo' },
  {
    value: 'uni-165',
    labelAr: 'جامعة كاليفورنيا - سان دييغو',
    labelEn: 'University of California - San Diego',
  },
  { value: 'uni-166', labelAr: 'جامعة كولورادو بولدر', labelEn: 'University of Colorado Boulder' },
  { value: 'uni-167', labelAr: 'جامعة ديلاوير', labelEn: 'University of Delaware' },
  {
    value: 'uni-168',
    labelAr: 'جامعة ماساتشوستس - أمهرست',
    labelEn: 'UNIVERSITY OF MASSACHUSETTS - AMHERST',
  },
  { value: 'uni-169', labelAr: 'جامعة سان دييغو', labelEn: 'University of San Diego' },
  {
    value: 'uni-170',
    labelAr: 'جامعة فرجينيا - الحرم الرئيسي',
    labelEn: 'UNIVERSITY OF VIRGINIA - MAIN CAMPUS',
  },
  {
    value: 'uni-171',
    labelAr: 'جامعة واشنطن - بوثيل',
    labelEn: 'UNIVERSITY OF WASHINGTON - BOTHELL',
  },
  {
    value: 'uni-172',
    labelAr: 'جامعة واشنطن - تاكوما',
    labelEn: 'University of Washington Tacoma',
  },
  {
    value: 'uni-173',
    labelAr: 'جامعة ولاية واشنطن - الحرم الرئيسي',
    labelEn: 'WASHINGTON STATE UNIVERSITY - MAIN CAMPUS',
  },
  { value: 'uni-174', labelAr: 'جامعة ميشيغان الغربية', labelEn: 'Western Michigan University' },
  { value: 'uni-175', labelAr: 'الجامعة الأمريكية (واشنطن)', labelEn: 'American University' },
  { value: 'uni-176', labelAr: 'كلية بيكون', labelEn: 'Beacon College' },
  { value: 'uni-177', labelAr: 'كلية بيركلي للموسيقى', labelEn: 'Berklee College of Music' },
  { value: 'uni-178', labelAr: 'كلية كلاركسون', labelEn: 'Clarkson College' },
  { value: 'uni-179', labelAr: 'كلية دارتموث', labelEn: 'DARTMOUTH COLLEGE' },
  { value: 'uni-180', labelAr: 'جامعة ديبول', labelEn: 'DePaul University' },
  {
    value: 'uni-181',
    labelAr: 'جامعة دومينيكان في كاليفورنيا',
    labelEn: 'Dominican University of California',
  },
  { value: 'uni-182', labelAr: 'جامعة إيموري', labelEn: 'EMORY UNIVERSITY' },
  { value: 'uni-183', labelAr: 'جامعة غالوديت', labelEn: 'Gallaudet University' },
  {
    value: 'uni-184',
    labelAr: 'جامعة جورج واشنطن - الحرم الرئيسي',
    labelEn: 'George Washington University - Main Campus',
  },
  { value: 'uni-185', labelAr: 'جامعة جورجتاون', labelEn: 'GEORGETOWN UNIVERSITY' },
  {
    value: 'uni-186',
    labelAr: 'كلية هالت الدولية لإدارة الأعمال',
    labelEn: 'Hult International Business School',
  },
  { value: 'uni-187', labelAr: 'جامعة جونز هوبكنز', labelEn: 'JOHNS HOPKINS UNIVERSITY' },
  { value: 'uni-188', labelAr: 'كلية كيندال', labelEn: 'Kendall College' },
  { value: 'uni-189', labelAr: 'جامعة ماريمونت', labelEn: 'Marymount University' },
  { value: 'uni-190', labelAr: 'كلية نازاريث', labelEn: 'Nazareth College' },
  {
    value: 'uni-191',
    labelAr: 'معهد روتشستر للتقنية',
    labelEn: 'Rochester Institute of Technology',
  },
  { value: 'uni-192', labelAr: 'جامعة روكهيرست', labelEn: 'Rockhurst University' },
  { value: 'uni-193', labelAr: 'جامعة تافتس', labelEn: 'TUFTS UNIVERSITY' },
  { value: 'uni-194', labelAr: 'جامعة بريدجبورت', labelEn: 'University of Bridgeport' },
  { value: 'uni-195', labelAr: 'جامعة إنديانابوليس', labelEn: 'University of Indianapolis' },
  { value: 'uni-196', labelAr: 'جامعة لا فيرن', labelEn: 'University of La Verne' },
  { value: 'uni-197', labelAr: 'جامعة روتشستر', labelEn: 'University of Rochester' },
  {
    value: 'uni-198',
    labelAr: 'جامعة واشنطن في سانت لويس',
    labelEn: 'Washington University in St. Louis',
  },
  { value: 'uni-199', labelAr: 'جامعة ويستكليف', labelEn: 'Westcliff University' },
  { value: 'uni-200', labelAr: 'بيربيك، جامعة لندن', labelEn: 'Birkbeck, University of London' },
  { value: 'uni-201', labelAr: 'جامعة برمنغهام سيتي', labelEn: 'Birmingham City University' },
  { value: 'uni-202', labelAr: 'جامعة بورنموث', labelEn: 'Bournemouth University' },
  { value: 'uni-203', labelAr: 'جامعة برونيل لندن', labelEn: 'Brunel University London' },
  {
    value: 'uni-204',
    labelAr: 'جامعة كارديف متروبوليتان',
    labelEn: 'Cardiff Metropolitan University',
  },
  { value: 'uni-205', labelAr: 'جامعة كارديف', labelEn: 'Cardiff University' },
  { value: 'uni-206', labelAr: 'سيتي، جامعة لندن', labelEn: 'City, Univerity of London' },
  { value: 'uni-207', labelAr: 'جامعة كينغستون', labelEn: 'Kingston University' },
  { value: 'uni-208', labelAr: 'جامعة لندن ساوث بانك', labelEn: 'London South Bank University' },
  { value: 'uni-209', labelAr: 'جامعة نيوكاسل', labelEn: 'Newcastle University' },
  { value: 'uni-210', labelAr: 'جامعة كوينز بلفاست', labelEn: "Queen's University Belfast" },
  {
    value: 'uni-211',
    labelAr: 'جامعة لندن (SOAS) لدراسات الشرق وأفريقيا',
    labelEn: 'SOAS University of London',
  },
  {
    value: 'uni-212',
    labelAr: 'جامعة سولنت - ساوثهامبتون',
    labelEn: 'Solent University | Southampton',
  },
  { value: 'uni-213', labelAr: 'جامعة أبردين', labelEn: 'University of Aberdeen' },
  { value: 'uni-214', labelAr: 'جامعة باث', labelEn: 'University of Bath' },
  { value: 'uni-215', labelAr: 'جامعة بيدفوردشير', labelEn: 'University of Bedfordshire' },
  { value: 'uni-216', labelAr: 'جامعة برمنغهام', labelEn: 'University of Birmingham' },
  { value: 'uni-217', labelAr: 'جامعة بولتون', labelEn: 'University of Bolton' },
  { value: 'uni-218', labelAr: 'جامعة برايتون', labelEn: 'University of Brighton' },
  { value: 'uni-219', labelAr: 'جامعة وسط لانكشاير', labelEn: 'University of Central Lancashire' },
  { value: 'uni-220', labelAr: 'جامعة ديربي', labelEn: 'University of Derby' },
  { value: 'uni-221', labelAr: 'جامعة دندي', labelEn: 'University of Dundee' },
  { value: 'uni-222', labelAr: 'جامعة درم', labelEn: 'University of Durham' },
  { value: 'uni-223', labelAr: 'جامعة إيست أنجليا', labelEn: 'University of East Anglia' },
  { value: 'uni-224', labelAr: 'جامعة شرق لندن', labelEn: 'University of East London' },
  { value: 'uni-225', labelAr: 'جامعة إسكس', labelEn: 'University of Essex' },
  { value: 'uni-226', labelAr: 'جامعة إكستر', labelEn: 'University of Exeter' },
  { value: 'uni-227', labelAr: 'جامعة غلاسكو', labelEn: 'University of Glasgow' },
  { value: 'uni-228', labelAr: 'جامعة غلوسترشير', labelEn: 'University of Gloucestershire' },
  { value: 'uni-229', labelAr: 'جامعة غرينتش', labelEn: 'University of Greenwich' },
  { value: 'uni-230', labelAr: 'جامعة هيرتفوردشير', labelEn: 'University of Hertfordshire' },
  { value: 'uni-231', labelAr: 'جامعة هال', labelEn: 'University of Hull' },
  { value: 'uni-232', labelAr: 'جامعة كنت', labelEn: 'University of Kent' },
  { value: 'uni-233', labelAr: 'جامعة ليدز', labelEn: 'University of Leeds' },
  { value: 'uni-234', labelAr: 'جامعة ليستر', labelEn: 'University of Leicester' },
  { value: 'uni-235', labelAr: 'جامعة لينكولن', labelEn: 'University of Lincoln' },
  { value: 'uni-236', labelAr: 'جامعة ليفربول', labelEn: 'University of Liverpool' },
  { value: 'uni-237', labelAr: 'جامعة نورثهامبتون', labelEn: 'University of Northampton' },
  {
    value: 'uni-238',
    labelAr: 'جامعة نورثمبريا في نيوكاسل',
    labelEn: 'University of Northumbria at Newcastle',
  },
  { value: 'uni-239', labelAr: 'جامعة نوتنغهام', labelEn: 'University of Nottingham' },
  { value: 'uni-240', labelAr: 'جامعة بليموث', labelEn: 'University of Plymouth' },
  { value: 'uni-241', labelAr: 'جامعة بورتسموث', labelEn: 'University of Portsmouth' },
  { value: 'uni-242', labelAr: 'جامعة ريدينغ', labelEn: 'University of Reading' },
  { value: 'uni-243', labelAr: 'جامعة سالفورد', labelEn: 'University of Salford' },
  { value: 'uni-244', labelAr: 'جامعة شيفيلد', labelEn: 'University of Sheffield' },
  { value: 'uni-245', labelAr: 'جامعة جنوب ويلز', labelEn: 'University of South Wales' },
  { value: 'uni-246', labelAr: 'جامعة ساوثهامبتون', labelEn: 'University of Southampton' },
  { value: 'uni-247', labelAr: 'جامعة سانت أندروز', labelEn: 'University of St Andrews' },
  { value: 'uni-248', labelAr: 'جامعة ستيرلينغ', labelEn: 'University of Stirling' },
  { value: 'uni-249', labelAr: 'جامعة ستراثكلايد', labelEn: 'University of Strathclyde' },
  { value: 'uni-250', labelAr: 'جامعة سندرلاند', labelEn: 'University of Sunderland' },
  { value: 'uni-251', labelAr: 'جامعة ساري', labelEn: 'University of Surrey' },
  { value: 'uni-252', labelAr: 'جامعة ساسكس', labelEn: 'University of Sussex' },
  { value: 'uni-253', labelAr: 'جامعة تيسايد', labelEn: 'University of Teesside' },
  { value: 'uni-254', labelAr: 'جامعة الفنون في لندن', labelEn: 'University of the Arts London' },
  { value: 'uni-255', labelAr: 'جامعة غرب إنجلترا', labelEn: 'University of the West of England' },
  {
    value: 'uni-256',
    labelAr: 'جامعة غرب اسكتلندا',
    labelEn: 'University of the West of Scotland',
  },
  { value: 'uni-257', labelAr: 'جامعة أولستر', labelEn: 'University of Ulster' },
  { value: 'uni-258', labelAr: 'جامعة وستمنستر', labelEn: 'University of Westminster' },
  { value: 'uni-259', labelAr: 'جامعة ولفرهامبتون', labelEn: 'University of Wolverhampton' },
  { value: 'uni-260', labelAr: 'جامعة يورك', labelEn: 'University of York' },
  {
    value: 'uni-261',
    labelAr: 'جامعة الفنون الإبداعية',
    labelEn: 'University for the Creative Arts‎',
  },
  { value: 'uni-262', labelAr: 'جامعة أكاديا', labelEn: 'Acadia University' },
  { value: 'uni-263', labelAr: 'جامعة ألغوما', labelEn: 'Algoma University' },
  { value: 'uni-264', labelAr: 'كلية ألغونكوين', labelEn: 'Algonquin College' },
  { value: 'uni-265', labelAr: 'جامعة بيشوبس', labelEn: 'Bishops University' },
  { value: 'uni-266', labelAr: 'جامعة براندون', labelEn: 'Brandon University' },
  { value: 'uni-267', labelAr: 'كلية بريشيا الجامعية', labelEn: 'Brescia University College' },
  { value: 'uni-268', labelAr: 'جامعة بروك', labelEn: 'Brock University' },
  { value: 'uni-269', labelAr: 'كلية كاموسون', labelEn: 'Camosun College' },
  { value: 'uni-270', labelAr: 'كلية كامبيون', labelEn: 'Campion College' },
  { value: 'uni-271', labelAr: 'كلية كانادور', labelEn: 'Canadore College' },
  { value: 'uni-272', labelAr: 'جامعة كابيلانو', labelEn: 'Capilano University' },
  { value: 'uni-273', labelAr: 'جامعة كارلتون', labelEn: 'Carleton University' },
  { value: 'uni-274', labelAr: 'كلية سنتينيال', labelEn: 'Centennial College' },
  {
    value: 'uni-275',
    labelAr: 'كلية جامعة سانت بونيفاس',
    labelEn: 'College University de Saint-Boniface',
  },
  { value: 'uni-276', labelAr: 'جامعة كونكورديا', labelEn: 'Concordia University' },
  { value: 'uni-277', labelAr: 'كلية كونستوغا', labelEn: 'Conestoga College' },
  { value: 'uni-278', labelAr: 'جامعة دالهوزي', labelEn: 'Dalhousie University' },
  { value: 'uni-279', labelAr: 'كلية دوغلاس', labelEn: 'Douglas College' },
  {
    value: 'uni-280',
    labelAr: 'جامعة الأمم الأولى الكندية',
    labelEn: 'First Nations University of Canada',
  },
  { value: 'uni-281', labelAr: 'كلية جورج براون', labelEn: 'George Brown College' },
  { value: 'uni-282', labelAr: 'جامعة غرانت ماكإيوان', labelEn: 'Grant MacEwan University' },
  { value: 'uni-283', labelAr: 'كلية HEC مونتريال لإدارة الأعمال', labelEn: 'HEC Monterial' },
  { value: 'uni-284', labelAr: 'كلية هَمبر', labelEn: 'Humber College' },
  { value: 'uni-285', labelAr: 'كلية هيورون الجامعية', labelEn: 'Huron University College' },
  {
    value: 'uni-286',
    labelAr: 'كلية كينغز الجامعية (جامعة غرب أونتاريو)',
    labelEn: "King's University College (University of Western Ontario)‎",
  },
  {
    value: 'uni-287',
    labelAr: 'جامعة كوانتلن التقنية',
    labelEn: 'Kwantlen Polytechnic University',
  },
  { value: 'uni-288', labelAr: 'جامعة ليكهيد', labelEn: 'Lakehead University' },
  { value: 'uni-289', labelAr: 'كلية لانغارا', labelEn: 'Langara College' },
  {
    value: 'uni-290',
    labelAr: 'جامعة لورنتيان في سدبري',
    labelEn: 'Laurentian University of Sudbury',
  },
  { value: 'uni-291', labelAr: 'جامعة ماكغيل', labelEn: 'McGill University' },
  { value: 'uni-292', labelAr: 'جامعة ماكماستر', labelEn: 'McMaster University' },
  {
    value: 'uni-293',
    labelAr: 'جامعة ميموريال نيوفاوندلاند',
    labelEn: 'Memorial University of Newfoundland',
  },
  { value: 'uni-294', labelAr: 'جامعة ماونت أليسون', labelEn: 'Mount Allison University' },
  { value: 'uni-295', labelAr: 'جامعة ماونت رويال', labelEn: 'Mount Royal University' },
  {
    value: 'uni-296',
    labelAr: 'جامعة ماونت سانت فينسنت',
    labelEn: 'Mount Saint Vincent University',
  },
  { value: 'uni-297', labelAr: 'كلية نياغرا', labelEn: 'Niagara College' },
  { value: 'uni-298', labelAr: 'جامعة نيبيسينغ', labelEn: 'Nipissing University' },
  { value: 'uni-299', labelAr: 'كلية أوكاناغان', labelEn: 'Okanagan College' },
  { value: 'uni-300', labelAr: 'كلية بورتاج', labelEn: 'Portage College' },
  {
    value: 'uni-301',
    labelAr: 'جامعة كوينز في كينغستون',
    labelEn: 'Queens University at Kingston',
  },
  { value: 'uni-302', labelAr: 'جامعة سانت ماري', labelEn: 'Saint Marys University' },
  { value: 'uni-303', labelAr: 'معهد سايت التقني', labelEn: 'SAIT Polytechnic' },
  { value: 'uni-304', labelAr: 'كلية سو', labelEn: 'Sault College' },
  { value: 'uni-305', labelAr: 'كلية سلكيرك', labelEn: 'Selkirk College' },
  { value: 'uni-306', labelAr: 'كلية سينيكا', labelEn: 'Seneca College' },
  { value: 'uni-307', labelAr: 'كلية شيريدان', labelEn: 'Sheridan College' },
  { value: 'uni-308', labelAr: 'جامعة سايمون فريزر', labelEn: 'Simon Fraser University' },
  {
    value: 'uni-309',
    labelAr: 'جامعة سانت فرانسيس إكزافيير',
    labelEn: 'St Francis Xavier University',
  },
  { value: 'uni-310', labelAr: 'جامعة سانت توماس', labelEn: 'St Thomas University' },
  { value: 'uni-311', labelAr: 'جامعة سانت جيروم', labelEn: "St. Jerome's University" },
  { value: 'uni-312', labelAr: 'كلية سانت لورنس', labelEn: 'St. Lawrence College' },
  { value: 'uni-313', labelAr: 'كلية سانت توماس مور', labelEn: 'St.Thomas More College' },
  {
    value: 'uni-314',
    labelAr: 'جامعة بريتيش كولومبيا',
    labelEn: 'The University of British Columbia',
  },
  { value: 'uni-315', labelAr: 'جامعة ليثبريدج', labelEn: 'The University of Lethbridge' },
  { value: 'uni-316', labelAr: 'جامعة ريجاينا', labelEn: 'The University of Regina' },
  { value: 'uni-317', labelAr: 'جامعة غرب أونتاريو', labelEn: 'The University of Western Ontario' },
  { value: 'uni-318', labelAr: 'جامعة تومبسون ريفرز', labelEn: 'Thompson Rivers University' },
  {
    value: 'uni-319',
    labelAr: 'جامعة تورونتو متروبوليتان',
    labelEn: 'Toronto Metropolitan University',
  },
  { value: 'uni-320', labelAr: 'جامعة ترينت', labelEn: 'Trent University' },
  {
    value: 'uni-321',
    labelAr: 'جامعة كيبك في شيكوتيمي',
    labelEn: 'Université du Québec à Chicoutimi',
  },
  {
    value: 'uni-322',
    labelAr: 'جامعة كيبك في ريموسكي',
    labelEn: 'Université du Québec à Rimouski',
  },
  {
    value: 'uni-323',
    labelAr: 'جامعة كيبك في ترois-ريفيير',
    labelEn: 'Université du Québec a Trois-Rivières',
  },
  {
    value: 'uni-324',
    labelAr: 'جامعة كيبك في أبيتيبي تيميسكامينغ',
    labelEn: 'Université du Québec en Abitibi-Témiscamingue',
  },
  { value: 'uni-325', labelAr: 'جامعة سانت آن', labelEn: 'Université Sainte-Anne' },
  { value: 'uni-326', labelAr: 'جامعة مونكتون', labelEn: 'University de Moncton' },
  { value: 'uni-327', labelAr: 'جامعة مونتريال', labelEn: 'University de Montreal' },
  {
    value: 'uni-328',
    labelAr: 'جامعة كيبك - المدرسة الوطنية للإدارة العامة',
    labelEn: 'University de Quebec Ecole nationale dadministration publique',
  },
  {
    value: 'uni-329',
    labelAr: 'جامعة كيبك (التعليم عن بعد)',
    labelEn: 'University de Quebec Tele-university (now affiliated with UQAM)‎',
  },
  {
    value: 'uni-330',
    labelAr: 'جامعة كيبك في أوتاوايس',
    labelEn: 'University de Quebec en Outaouais',
  },
  { value: 'uni-331', labelAr: 'جامعة شيربروك', labelEn: 'University de Sherbrooke' },
  { value: 'uni-332', labelAr: 'جامعة كيبك في مونتريال', labelEn: 'University du Quebec Montreal' },
  { value: 'uni-333', labelAr: 'جامعة لافال', labelEn: 'University Laval' },
  { value: 'uni-334', labelAr: 'جامعة وينيبيغ', labelEn: 'University of Winnipeg' },
  { value: 'uni-335', labelAr: 'جامعة ألبرتا', labelEn: 'University of Alberta' },
  { value: 'uni-336', labelAr: 'جامعة كالغاري', labelEn: 'University of Calgary' },
  { value: 'uni-337', labelAr: 'جامعة غويلف', labelEn: 'University of Guelph' },
  { value: 'uni-338', labelAr: 'جامعة كينغز كوليدج', labelEn: 'University of Kings College' },
  { value: 'uni-339', labelAr: 'جامعة مانيتوبا', labelEn: 'University of Manitoba' },
  { value: 'uni-340', labelAr: 'جامعة نيو برونزويك', labelEn: 'University of New Brunswick' },
  {
    value: 'uni-341',
    labelAr: 'جامعة شمال بريتيش كولومبيا',
    labelEn: 'University of Northern British Columbia',
  },
  { value: 'uni-342', labelAr: 'جامعة أوتاوا', labelEn: 'University of Ottawa' },
  {
    value: 'uni-343',
    labelAr: 'جامعة الأمير إدوارد أيلاند',
    labelEn: 'University of Prince Edward Island',
  },
  { value: 'uni-344', labelAr: 'جامعة ساسكاتشوان', labelEn: 'University of Saskatchewan' },
  {
    value: 'uni-345',
    labelAr: 'جامعة كلية سانت مايكل',
    labelEn: 'University of St Michaels College',
  },
  { value: 'uni-346', labelAr: 'جامعة وادي فريزر', labelEn: 'University of The Fraser Valley' },
  { value: 'uni-347', labelAr: 'جامعة تورونتو', labelEn: 'University of Toronto' },
  { value: 'uni-348', labelAr: 'جامعة ترينيتي كوليدج', labelEn: 'University of Trinity College' },
  { value: 'uni-349', labelAr: 'جامعة فيكتوريا', labelEn: 'University of Victoria' },
  { value: 'uni-350', labelAr: 'جامعة واترلو', labelEn: 'University of Waterloo' },
  { value: 'uni-351', labelAr: 'جامعة وندسور', labelEn: 'University of Windsor' },
  { value: 'uni-352', labelAr: 'جامعة جزيرة فانكوفر', labelEn: 'Vancouver Island University' },
  {
    value: 'uni-353',
    labelAr: 'جامعة فيكتوريا - تورونتو',
    labelEn: 'Victoria University- Toronto',
  },
  { value: 'uni-354', labelAr: 'جامعة وسترن', labelEn: 'Western University' },
  { value: 'uni-355', labelAr: 'جامعة ويلفريد لورييه', labelEn: 'Wilfrid Laurier University' },
  { value: 'uni-356', labelAr: 'جامعة يورك (كندا)', labelEn: 'York University' },
  {
    value: 'uni-357',
    labelAr: 'جامعة فيرلي ديكنسون - حرم فانكوفر',
    labelEn: 'Fairleigh Dickinson University Vancouver Campus',
  },
  { value: 'uni-358', labelAr: 'كلية لاسال - فانكوفر', labelEn: 'Lasalle College Vancouver' },
  { value: 'uni-359', labelAr: 'معهد تريباس - كيبك', labelEn: 'Trebas Institute Quebec Inc' },
  { value: 'uni-360', labelAr: 'جامعة أنهوي', labelEn: 'Anhui University' },
  { value: 'uni-361', labelAr: 'جامعة بيهانغ', labelEn: 'Beihang University' },
  {
    value: 'uni-362',
    labelAr: 'معهد بكين للإدارة (أكاديمية العلوم الصينية)',
    labelEn: 'Beijing Institute of Management)Chinese Academy of Sciences',
  },
  { value: 'uni-363', labelAr: 'معهد بكين للتقنية', labelEn: 'Beijing Institute of Technology' },
  {
    value: 'uni-364',
    labelAr: 'جامعة بكين للدراسات الدولية',
    labelEn: 'Beijing International Studies University',
  },
  { value: 'uni-365', labelAr: 'جامعة بكين جياوتونغ', labelEn: 'Beijing Jiaotong University' },
  {
    value: 'uni-366',
    labelAr: 'جامعة بكين للغة والثقافة',
    labelEn: 'Beijing Language and Culture University',
  },
  { value: 'uni-367', labelAr: 'جامعة بكين التربوية', labelEn: 'Beijing Normal University' },
  { value: 'uni-368', labelAr: 'جامعة بكين للتقنية', labelEn: 'Beijing University of Technology' },
  {
    value: 'uni-369',
    labelAr: 'جامعة وسط الصين التربوية',
    labelEn: 'Central China Normal University',
  },
  {
    value: 'uni-370',
    labelAr: 'جامعة الجنوب الأوسط (سنترال ساوث)',
    labelEn: 'Central South University',
  },
  {
    value: 'uni-371',
    labelAr: 'الجامعة المركزية للمالية والاقتصاد',
    labelEn: 'Central University of Finance and Economics',
  },
  { value: 'uni-372', labelAr: 'جامعة تشانغآن', labelEn: "Chang'an University" },
  {
    value: 'uni-373',
    labelAr: 'جامعة الصين للشؤون الخارجية',
    labelEn: 'China Foreign Affairs University',
  },
  { value: 'uni-374', labelAr: 'جامعة تشونغتشينغ', labelEn: 'Chongqing University' },
  {
    value: 'uni-375',
    labelAr: 'جامعة هونغ كونغ المدينة (سيتي)',
    labelEn: 'City University of Hong Kong',
  },
  { value: 'uni-376', labelAr: 'جامعة داليان للتقنية', labelEn: 'Dalian University of Technology' },
  { value: 'uni-377', labelAr: 'جامعة دونغهوا', labelEn: 'Donghua University' },
  {
    value: 'uni-378',
    labelAr: 'جامعة شرق الصين التربوية',
    labelEn: 'East China Normal University',
  },
  {
    value: 'uni-379',
    labelAr: 'جامعة شرق الصين للعلوم والتقنية',
    labelEn: 'East China University of Science and Technology',
  },
  { value: 'uni-380', labelAr: 'جامعة فودان', labelEn: 'Fudan University' },
  { value: 'uni-381', labelAr: 'جامعة فوتشو', labelEn: 'Fuzhou University' },
  { value: 'uni-382', labelAr: 'جامعة قوانغشي', labelEn: 'Guangxi University' },
  {
    value: 'uni-383',
    labelAr: 'جامعة هاربين الهندسية',
    labelEn: 'Harbin Engineering University (CSTIND',
  },
  {
    value: 'uni-384',
    labelAr: 'معهد هاربين للتقنية',
    labelEn: 'Harbin Institute of Technology (CSTIND) ‎',
  },
  { value: 'uni-385', labelAr: 'جامعة هوهاي', labelEn: 'Hohai University' },
  {
    value: 'uni-386',
    labelAr: 'جامعة هونغ كونغ المعمدانية',
    labelEn: 'Hong Kong Baptist University',
  },
  {
    value: 'uni-387',
    labelAr: 'جامعة هواتشونغ الزراعية',
    labelEn: 'Huazhong Agricultural University',
  },
  {
    value: 'uni-388',
    labelAr: 'جامعة هواتشونغ للعلوم والتقنية',
    labelEn: 'Huazhong University of Science and Technology',
  },
  { value: 'uni-389', labelAr: 'جامعة هونان التربوية', labelEn: 'Hunan Normal University' },
  { value: 'uni-390', labelAr: 'جامعة هونان', labelEn: 'Hunan University' },
  { value: 'uni-391', labelAr: 'جامعة منغوليا الداخلية', labelEn: 'Inner Mongolia University' },
  { value: 'uni-392', labelAr: 'جامعة جيانغنان', labelEn: 'Jiangnan University' },
  { value: 'uni-393', labelAr: 'جامعة جيلين', labelEn: 'Jilin University' },
  { value: 'uni-394', labelAr: 'جامعة جينان', labelEn: 'JiNan University' },
  { value: 'uni-395', labelAr: 'جامعة لانتشو', labelEn: 'Lanzhou University' },
  { value: 'uni-396', labelAr: 'جامعة لياونينغ', labelEn: 'Liaoning University' },
  { value: 'uni-397', labelAr: 'جامعة لينغنان', labelEn: 'Lingnan University' },
  {
    value: 'uni-398',
    labelAr: 'المركز الطبي لجامعة فودان',
    labelEn: 'Medical Center of Fudan University',
  },
  {
    value: 'uni-399',
    labelAr: 'جامعة الصين للقوميات (مينزو)',
    labelEn: 'Minzu University of China',
  },
  { value: 'uni-400', labelAr: 'جامعة نانتشانغ', labelEn: 'Nanchang University' },
  { value: 'uni-401', labelAr: 'جامعة نانجينغ', labelEn: 'Nanjing University' },
  {
    value: 'uni-402',
    labelAr: 'جامعة نانجينغ للعلوم والتقنية',
    labelEn: 'Nanjing University of Science and Technology (CSTIND)‎',
  },
  { value: 'uni-403', labelAr: 'جامعة نانكاي', labelEn: 'Nankai University' },
  {
    value: 'uni-404',
    labelAr: 'الجامعة الوطنية لتقنية الدفاع',
    labelEn: 'National University of Defense Technology',
  },
  {
    value: 'uni-405',
    labelAr: 'جامعة شمال شرق الصين التربوية',
    labelEn: 'Northeast Normal University',
  },
  {
    value: 'uni-406',
    labelAr: 'الجامعة الشمالية الشرقية (الصين)',
    labelEn: 'Northeastern University',
  },
  { value: 'uni-407', labelAr: 'جامعة الشمال الغربي', labelEn: 'Northwest University' },
  {
    value: 'uni-408',
    labelAr: 'الجامعة التقنية الشمالية الغربية',
    labelEn: 'Northwestern Polytechnical University',
  },
  { value: 'uni-409', labelAr: 'جامعة الصين للمحيطات', labelEn: 'Ocean University of China' },
  { value: 'uni-410', labelAr: 'جامعة بكين', labelEn: 'Peking University' },
  {
    value: 'uni-411',
    labelAr: 'جامعة الصين الشعبية (رنمين)',
    labelEn: 'Renmin University of China( People University of China)‎',
  },
  {
    value: 'uni-412',
    labelAr: 'الجامعة الطبية العسكرية الثانية',
    labelEn: 'Second Military Medical University',
  },
  { value: 'uni-413', labelAr: 'جامعة شنشي التربوية', labelEn: 'Shaanxi Normal University' },
  { value: 'uni-414', labelAr: 'جامعة شاندونغ', labelEn: 'Shandong University' },
  { value: 'uni-415', labelAr: 'جامعة شنغهاي جياوتونغ', labelEn: 'Shanghai Jiao tong University' },
  { value: 'uni-416', labelAr: 'جامعة شنغهاي', labelEn: 'Shanghai University' },
  {
    value: 'uni-417',
    labelAr: 'جامعة شنغهاي للمالية والاقتصاد',
    labelEn: 'Shanghai University of Finance & Economics',
  },
  { value: 'uni-418', labelAr: 'جامعة سيتشوان', labelEn: 'Sichuan University' },
  { value: 'uni-419', labelAr: 'جامعة سوتشو', labelEn: 'Soochow University' },
  {
    value: 'uni-420',
    labelAr: 'جامعة جنوب الصين التربوية',
    labelEn: 'South China Normal University',
  },
  {
    value: 'uni-421',
    labelAr: 'جامعة جنوب الصين للتقنية',
    labelEn: 'South China University of Technology',
  },
  { value: 'uni-422', labelAr: 'جامعة جنوب شرق الصين', labelEn: 'Southeast University' },
  {
    value: 'uni-423',
    labelAr: 'الجامعة الجنوبية للعلوم والتقنية',
    labelEn: 'Southern University of Science and Technology',
  },
  {
    value: 'uni-424',
    labelAr: 'جامعة الجنوب الغربي جياوتونغ',
    labelEn: 'Southwest Jiaotong University',
  },
  { value: 'uni-425', labelAr: 'جامعة الجنوب الغربي', labelEn: 'Southwest University' },
  {
    value: 'uni-426',
    labelAr: 'جامعة الجنوب الغربي للمالية والاقتصاد',
    labelEn: 'Southwestern University of Finance and Economics',
  },
  { value: 'uni-427', labelAr: 'جامعة صن يات صن', labelEn: 'Sun Yat-sen University' },
  {
    value: 'uni-428',
    labelAr: 'جامعة تاييوان للتقنية',
    labelEn: 'Taiyuan University of Technology',
  },
  {
    value: 'uni-429',
    labelAr: 'جامعة هونغ كونغ الصينية',
    labelEn: 'The Chinese University of Hong Kong (CUHK)‎',
  },
  {
    value: 'uni-430',
    labelAr: 'الجامعة الطبية العسكرية الرابعة',
    labelEn: 'The Fourth Military Medical University',
  },
  {
    value: 'uni-431',
    labelAr: 'أكاديمية هونغ كونغ للفنون الأدائية',
    labelEn: 'The Hong Kong Academy for Performing Arts',
  },
  {
    value: 'uni-432',
    labelAr: 'معهد هونغ كونغ للتربية',
    labelEn: 'The Hong Kong Institute of Education',
  },
  {
    value: 'uni-433',
    labelAr: 'جامعة هونغ كونغ التقنية (بوليتكنيك)',
    labelEn: 'The Hong Kong Polytechnic University',
  },
  {
    value: 'uni-434',
    labelAr: 'جامعة هونغ كونغ للعلوم والتقنية',
    labelEn: 'The Hong Kong University of Science and Technology',
  },
  { value: 'uni-435', labelAr: 'جامعة هونغ كونغ', labelEn: 'The University of Hong Kong' },
  { value: 'uni-436', labelAr: 'جامعة تيانجين', labelEn: 'Tianjin University' },
  { value: 'uni-437', labelAr: 'جامعة تونغجي', labelEn: 'Tongji University' },
  { value: 'uni-438', labelAr: 'جامعة تسينغهوا', labelEn: 'Tsinghua University' },
  {
    value: 'uni-439',
    labelAr: 'جامعة الصين للعلوم والتقنية الإلكترونية',
    labelEn: 'University of Electronic Science and Technology of china',
  },
  {
    value: 'uni-440',
    labelAr: 'جامعة الأعمال والاقتصاد الدولية',
    labelEn: 'University of International Business and Economics',
  },
  {
    value: 'uni-441',
    labelAr: 'جامعة العلاقات الدولية',
    labelEn: 'University of International Relations',
  },
  {
    value: 'uni-442',
    labelAr: 'جامعة بكين للعلوم والتقنية',
    labelEn: 'University of Science and Technology Beijing',
  },
  {
    value: 'uni-443',
    labelAr: 'جامعة الصين للعلوم والتقنية',
    labelEn: 'University of Science and Technology of China',
  },
  { value: 'uni-444', labelAr: 'جامعة ووهان', labelEn: 'Wuhan University' },
  { value: 'uni-445', labelAr: 'جامعة ووهان للتقنية', labelEn: 'Wuhan University of Technology' },
  { value: 'uni-446', labelAr: 'جامعة شيامن', labelEn: 'Xiamen University' },
  { value: 'uni-447', labelAr: 'جامعة شيان جياوتونغ', labelEn: "Xi'an Jiaotong University" },
  { value: 'uni-448', labelAr: 'جامعة شيديان', labelEn: 'Xidian University' },
  { value: 'uni-449', labelAr: 'جامعة شينجيانغ', labelEn: 'Xinjiang University' },
  { value: 'uni-450', labelAr: 'جامعة يانبيان', labelEn: 'Yanbian University' },
  { value: 'uni-451', labelAr: 'جامعة يوننان', labelEn: 'Yunnan University' },
  { value: 'uni-452', labelAr: 'جامعة تشجيانغ', labelEn: 'Zhejiang University' },
  { value: 'uni-453', labelAr: 'جامعة تشنغتشو', labelEn: 'Zhengzhou University' },
  { value: 'uni-454', labelAr: 'جامعة هونغ كونغ شو يان', labelEn: 'Hong Kong Shue Yan University' },
  {
    value: 'uni-455',
    labelAr: 'أكاديمية السادات للعلوم الإدارية',
    labelEn: 'Sadat Academy for Management Sciences',
  },
  { value: 'uni-456', labelAr: 'جامعة أسيوط', labelEn: 'Assiut University' },
  { value: 'uni-457', labelAr: 'جامعة الأزهر', labelEn: 'Al-Azhar University' },
  { value: 'uni-458', labelAr: 'جامعة الإسكندرية', labelEn: 'Alexandria University' },
  { value: 'uni-459', labelAr: 'جامعة الزقازيق', labelEn: 'Zagazig University' },
  { value: 'uni-460', labelAr: 'جامعة السويس', labelEn: 'Suez University' },
  {
    value: 'uni-461',
    labelAr: 'جامعة العاصمة',
    labelEn: 'Al-Asema University (Capital University)',
  },
  { value: 'uni-462', labelAr: 'جامعة الفيوم', labelEn: 'Fayoum University' },
  { value: 'uni-463', labelAr: 'جامعة القاهرة', labelEn: 'Cairo University' },
  { value: 'uni-464', labelAr: 'جامعة المنصورة', labelEn: 'Mansoura University' },
  { value: 'uni-465', labelAr: 'جامعة المنوفية', labelEn: 'Menoufia University' },
  { value: 'uni-466', labelAr: 'جامعة المنيا', labelEn: 'Minia University' },
  { value: 'uni-467', labelAr: 'جامعة دمنهور', labelEn: 'Damanhour University' },
  { value: 'uni-468', labelAr: 'جامعة دمياط', labelEn: 'Damietta University' },
  { value: 'uni-469', labelAr: 'جامعة طنطا', labelEn: 'Tanta University' },
  { value: 'uni-470', labelAr: 'جامعة عين شمس', labelEn: 'Ain Shams University' },
  { value: 'uni-471', labelAr: 'جامعة قناة السويس', labelEn: 'Suez Canal University' },
  { value: 'uni-472', labelAr: 'جامعة كفر الشيخ', labelEn: 'Kafrelsheikh University' },
  {
    value: 'uni-473',
    labelAr: 'الجامعة الألمانية بالقاهرة',
    labelEn: 'German University in Cairo',
  },
  {
    value: 'uni-474',
    labelAr: 'الجامعة الأمريكية بالقاهرة',
    labelEn: 'American University in Cairo',
  },
  {
    value: 'uni-475',
    labelAr: 'الجامعة البريطانية في مصر',
    labelEn: 'The British University in Egypt',
  },
  { value: 'uni-476', labelAr: 'جامعة 6 اكتوبر', labelEn: 'October 6 University' },
  {
    value: 'uni-477',
    labelAr: 'جامعة الملك سلمان الدولية الأهلية',
    labelEn: 'King Salman International University',
  },
  { value: 'uni-478', labelAr: 'جامعة بدر بالقاهرة', labelEn: 'Badr University in Cairo' },
  { value: 'uni-479', labelAr: 'جامعة بني سويف', labelEn: 'Beni-Suef University' },
  {
    value: 'uni-480',
    labelAr: 'جامعة فاروس بالاسكندرية',
    labelEn: 'Pharos University in Alexandria',
  },
  {
    value: 'uni-481',
    labelAr: 'جامعة مصر للعلوم والتكنولوجيا',
    labelEn: 'Misr University for Science and Technology',
  },
  { value: 'uni-482', labelAr: 'فرع جامعة كوفنتري', labelEn: 'Coventry University Branch (Egypt)' },
  {
    value: 'uni-483',
    labelAr: 'فرع جامعة لندن بالقاهرة',
    labelEn: 'University of London Branch in Cairo',
  },
  {
    value: 'uni-484',
    labelAr: 'فرع جامعة وسط لانكشاير',
    labelEn: 'University of Central Lancashire Branch (Egypt)',
  },
  { value: 'uni-485', labelAr: 'الجامعة الأردنية', labelEn: 'The University of Jordan' },
  {
    value: 'uni-486',
    labelAr: 'الجامعة الألمانية الأردنية',
    labelEn: 'German Jordanian University',
  },
  { value: 'uni-487', labelAr: 'الجامعة الهاشمية', labelEn: 'The Hashemite University' },
  { value: 'uni-488', labelAr: 'جامعة آل البيت', labelEn: 'Al al-Bayt University' },
  { value: 'uni-489', labelAr: 'جامعة البلقاء التطبيقية', labelEn: 'Al-Balqa Applied University' },
  { value: 'uni-490', labelAr: 'جامعة الحسين بن طلال', labelEn: 'Al-Hussein Bin Talal University' },
  { value: 'uni-491', labelAr: 'جامعة الطفيلة التقنية', labelEn: 'Tafila Technical University' },
  {
    value: 'uni-492',
    labelAr: 'جامعة العلوم والتكنولوجيا',
    labelEn: 'Jordan University of Science and Technology',
  },
  { value: 'uni-493', labelAr: 'جامعة اليرموك', labelEn: 'Yarmouk University' },
  { value: 'uni-494', labelAr: 'جامعة مؤته', labelEn: 'Mutah University' },
  {
    value: 'uni-495',
    labelAr: 'جامعة بيدفوردشير في الأردن',
    labelEn: 'University of Bedfordshire in Jordan',
  },
  {
    value: 'uni-496',
    labelAr: 'الجامعة الأمريكية في مادبا',
    labelEn: 'American University of Madaba',
  },
  {
    value: 'uni-497',
    labelAr: 'الجامعة العربية المفتوحة بالأردن',
    labelEn: 'Arab Open University (Jordan Branch)',
  },
  { value: 'uni-498', labelAr: 'جامعة اربد الأهلية', labelEn: 'Irbid National University' },
  { value: 'uni-499', labelAr: 'جامعة الإسراء', labelEn: 'Isra University' },
  {
    value: 'uni-500',
    labelAr: 'جامعة الأميرة سمية للتكنولوجيا',
    labelEn: 'Princess Sumaya University for Technology',
  },
  { value: 'uni-501', labelAr: 'جامعة البترا', labelEn: 'Petra University' },
  {
    value: 'uni-502',
    labelAr: 'جامعة الحسين بن عبدالله الثاني التقنية',
    labelEn: 'Al Hussein Technical University',
  },
  { value: 'uni-503', labelAr: 'جامعة الزرقاء', labelEn: 'Zarqa University' },
  {
    value: 'uni-504',
    labelAr: 'جامعة الزيتونة الأردنية',
    labelEn: 'Al-Zaytoonah University of Jordan',
  },
  { value: 'uni-505', labelAr: 'جامعة الشرق الأوسط', labelEn: 'Middle East University' },
  {
    value: 'uni-506',
    labelAr: 'جامعة العقبة للتكنولوجيا',
    labelEn: 'Aqaba University of Technology',
  },
  {
    value: 'uni-507',
    labelAr: 'جامعة العقبة للعلوم الطبية',
    labelEn: 'Aqaba Medical Sciences University',
  },
  {
    value: 'uni-508',
    labelAr: 'جامعة العلوم الإسلامية العالمية',
    labelEn: 'World Islamic Sciences and Education University (WISE)',
  },
  {
    value: 'uni-509',
    labelAr: 'جامعة العلوم التطبيقية الخاصة',
    labelEn: 'Applied Science Private University',
  },
  { value: 'uni-510', labelAr: 'جامعة جدارا', labelEn: 'Jadara University' },
  { value: 'uni-511', labelAr: 'جامعة جرش', labelEn: 'Jerash University' },
  { value: 'uni-512', labelAr: 'جامعة عجلون الوطنية', labelEn: 'Ajloun National University' },
  { value: 'uni-513', labelAr: 'جامعة عمَّان الأهلية', labelEn: 'Al-Ahliyya Amman University' },
  { value: 'uni-514', labelAr: 'جامعة عمّان العربية', labelEn: 'Amman Arab University' },
  { value: 'uni-515', labelAr: 'جامعة فيلادلفيا', labelEn: 'Philadelphia University' },
  { value: 'uni-516', labelAr: 'أخرى**', labelEn: 'Others**' },
  {
    value: 'uni-517',
    labelAr: '**عند اختياراخرى تتيح للخبيرأوالمدرب كتابة التخصص',
    labelEn: '**عند اختياراخرى تتيح للخبيرأوالمدرب كتابة التخصص',
  },
];
