// <auto-generated />
using System;
using ExpertHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpertHub.Infrastructure.Migrations
{
    [DbContext(typeof(ExpertHubDbContext))]
    [Migration("20260830111129_M02AccessModel")]
    partial class M02AccessModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpertHub.Core.Domain.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalIdentityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("external_identity_id");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name_ar");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name_en");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit")
                        .HasColumnName("is_employee");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredCommunicationLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("preferred_communication_language");

                    b.Property<string>("PreferredUiLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("preferred_ui_language");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalIdentityId")
                        .IsUnique();

                    b.ToTable("APP_USER", (string)null);
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("attachment_id");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("checksum");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ScanStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("scan_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("storage_ref");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by");

                    b.HasKey("AttachmentId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ATTACHMENT", (string)null);
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.AuditLogEntry", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("AfterState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("before_state");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("capability_code");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("feature_code");

                    b.Property<bool>("LabelNeedsVerification")
                        .HasColumnType("bit")
                        .HasColumnName("label_needs_verification");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name_en");

                    b.HasKey("PermissionId");

                    b.HasIndex("FeatureCode")
                        .IsUnique();

                    b.ToTable("PERMISSION", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CapabilityCode = "CAP-01",
                            FeatureCode = "F-0101",
                            LabelNeedsVerification = true,
                            NameAr = "تقديم طلب",
                            NameEn = "Application Management — F-0101"
                        },
                        new
                        {
                            PermissionId = 2,
                            CapabilityCode = "CAP-01",
                            FeatureCode = "F-0102",
                            LabelNeedsVerification = true,
                            NameAr = "الترشيح",
                            NameEn = "Application Management — F-0102"
                        },
                        new
                        {
                            PermissionId = 3,
                            CapabilityCode = "CAP-01",
                            FeatureCode = "F-0104",
                            LabelNeedsVerification = true,
                            NameAr = "طلب إضافة",
                            NameEn = "Application Management — F-0104"
                        },
                        new
                        {
                            PermissionId = 4,
                            CapabilityCode = "CAP-01",
                            FeatureCode = "F-0105",
                            LabelNeedsVerification = true,
                            NameAr = "إدخال بيانات",
                            NameEn = "Application Management — F-0105"
                        },
                        new
                        {
                            PermissionId = 5,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0201",
                            LabelNeedsVerification = true,
                            NameAr = "الفرز الأولي",
                            NameEn = "Screening & Evaluation — F-0201"
                        },
                        new
                        {
                            PermissionId = 6,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0202",
                            LabelNeedsVerification = true,
                            NameAr = "جدولة المقابلة",
                            NameEn = "Screening & Evaluation — F-0202"
                        },
                        new
                        {
                            PermissionId = 7,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0203",
                            LabelNeedsVerification = true,
                            NameAr = "تقييم المقابلة",
                            NameEn = "Screening & Evaluation — F-0203"
                        },
                        new
                        {
                            PermissionId = 8,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0204",
                            LabelNeedsVerification = true,
                            NameAr = "قرار لجنة",
                            NameEn = "Screening & Evaluation — F-0204"
                        },
                        new
                        {
                            PermissionId = 9,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0205",
                            LabelNeedsVerification = true,
                            NameAr = "سير اعتماد",
                            NameEn = "Screening & Evaluation — F-0205"
                        },
                        new
                        {
                            PermissionId = 10,
                            CapabilityCode = "CAP-02",
                            FeatureCode = "F-0206",
                            LabelNeedsVerification = true,
                            NameAr = "توقيع المتقدم",
                            NameEn = "Screening & Evaluation — F-0206"
                        },
                        new
                        {
                            PermissionId = 11,
                            CapabilityCode = "CAP-03",
                            FeatureCode = "F-0301",
                            LabelNeedsVerification = true,
                            NameAr = "تفعيل الاتفاقية",
                            NameEn = "Agreement & Contract — F-0301"
                        },
                        new
                        {
                            PermissionId = 12,
                            CapabilityCode = "CAP-03",
                            FeatureCode = "F-0302",
                            LabelNeedsVerification = true,
                            NameAr = "تنبيهات الانتهاء",
                            NameEn = "Agreement & Contract — F-0302"
                        },
                        new
                        {
                            PermissionId = 13,
                            CapabilityCode = "CAP-03",
                            FeatureCode = "F-0303",
                            LabelNeedsVerification = true,
                            NameAr = "التجديد الإداري",
                            NameEn = "Agreement & Contract — F-0303"
                        },
                        new
                        {
                            PermissionId = 14,
                            CapabilityCode = "CAP-03",
                            FeatureCode = "F-0304",
                            LabelNeedsVerification = true,
                            NameAr = "ضبط حالة الاتفاقية",
                            NameEn = "Agreement & Contract — F-0304"
                        },
                        new
                        {
                            PermissionId = 15,
                            CapabilityCode = "CAP-03",
                            FeatureCode = "F-0305",
                            LabelNeedsVerification = true,
                            NameAr = "إلحاق خدمة جديدة",
                            NameEn = "Agreement & Contract — F-0305"
                        },
                        new
                        {
                            PermissionId = 16,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0401",
                            LabelNeedsVerification = true,
                            NameAr = "إنشاء ملف",
                            NameEn = "Trainer Profile — F-0401"
                        },
                        new
                        {
                            PermissionId = 17,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0402",
                            LabelNeedsVerification = true,
                            NameAr = "الملف الشامل",
                            NameEn = "Trainer Profile — F-0402"
                        },
                        new
                        {
                            PermissionId = 18,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0403",
                            LabelNeedsVerification = true,
                            NameAr = "التحديث الذاتي",
                            NameEn = "Trainer Profile — F-0403"
                        },
                        new
                        {
                            PermissionId = 19,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0404",
                            LabelNeedsVerification = true,
                            NameAr = "الخدمات",
                            NameEn = "Trainer Profile — F-0404"
                        },
                        new
                        {
                            PermissionId = 20,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0405",
                            LabelNeedsVerification = true,
                            NameAr = "سجل البرامج",
                            NameEn = "Trainer Profile — F-0405"
                        },
                        new
                        {
                            PermissionId = 21,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0406",
                            LabelNeedsVerification = true,
                            NameAr = "تقييمات المدرب",
                            NameEn = "Trainer Profile — F-0406"
                        },
                        new
                        {
                            PermissionId = 22,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0407",
                            LabelNeedsVerification = true,
                            NameAr = "عرض طلبات",
                            NameEn = "Trainer Profile — F-0407"
                        },
                        new
                        {
                            PermissionId = 23,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0408",
                            LabelNeedsVerification = true,
                            NameAr = "عرض بيانات",
                            NameEn = "Trainer Profile — F-0408"
                        },
                        new
                        {
                            PermissionId = 24,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0409",
                            LabelNeedsVerification = true,
                            NameAr = "كشف تعارض",
                            NameEn = "Trainer Profile — F-0409"
                        },
                        new
                        {
                            PermissionId = 25,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0410",
                            LabelNeedsVerification = true,
                            NameAr = "البحث والفلترة",
                            NameEn = "Trainer Profile — F-0410"
                        },
                        new
                        {
                            PermissionId = 26,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0411",
                            LabelNeedsVerification = true,
                            NameAr = "حالة ملف",
                            NameEn = "Trainer Profile — F-0411"
                        },
                        new
                        {
                            PermissionId = 27,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0412",
                            LabelNeedsVerification = true,
                            NameAr = "تغذية محرك",
                            NameEn = "Trainer Profile — F-0412"
                        },
                        new
                        {
                            PermissionId = 28,
                            CapabilityCode = "CAP-04",
                            FeatureCode = "F-0413",
                            LabelNeedsVerification = true,
                            NameAr = "إدارة سجل",
                            NameEn = "Trainer Profile — F-0413"
                        },
                        new
                        {
                            PermissionId = 29,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0501",
                            LabelNeedsVerification = true,
                            NameAr = "إنشاء طلب الإسناد",
                            NameEn = "Assignment & Matching — F-0501"
                        },
                        new
                        {
                            PermissionId = 30,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0502",
                            LabelNeedsVerification = true,
                            NameAr = "الترشيح الآلي",
                            NameEn = "Assignment & Matching — F-0502"
                        },
                        new
                        {
                            PermissionId = 31,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0503",
                            LabelNeedsVerification = true,
                            NameAr = "البحث والترشيح",
                            NameEn = "Assignment & Matching — F-0503"
                        },
                        new
                        {
                            PermissionId = 32,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0504",
                            LabelNeedsVerification = true,
                            NameAr = "موافقة المركز",
                            NameEn = "Assignment & Matching — F-0504"
                        },
                        new
                        {
                            PermissionId = 33,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0505",
                            LabelNeedsVerification = true,
                            NameAr = "عرض الإسناد",
                            NameEn = "Assignment & Matching — F-0505"
                        },
                        new
                        {
                            PermissionId = 34,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0506",
                            LabelNeedsVerification = true,
                            NameAr = "رفع واعتماد مادة",
                            NameEn = "Assignment & Matching — F-0506"
                        },
                        new
                        {
                            PermissionId = 35,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0507",
                            LabelNeedsVerification = true,
                            NameAr = "متابعة الارتباط",
                            NameEn = "Assignment & Matching — F-0507"
                        },
                        new
                        {
                            PermissionId = 36,
                            CapabilityCode = "CAP-05",
                            FeatureCode = "F-0508",
                            LabelNeedsVerification = true,
                            NameAr = "إلغاء الارتباط من",
                            NameEn = "Assignment & Matching — F-0508"
                        },
                        new
                        {
                            PermissionId = 37,
                            CapabilityCode = "CAP-06",
                            FeatureCode = "F-0601",
                            LabelNeedsVerification = true,
                            NameAr = "عرض المستحقات",
                            NameEn = "Entitlement Management — F-0601"
                        },
                        new
                        {
                            PermissionId = 38,
                            CapabilityCode = "CAP-06",
                            FeatureCode = "F-0602",
                            LabelNeedsVerification = true,
                            NameAr = "عرض المستحقات",
                            NameEn = "Entitlement Management — F-0602"
                        },
                        new
                        {
                            PermissionId = 39,
                            CapabilityCode = "CAP-06",
                            FeatureCode = "F-0603",
                            LabelNeedsVerification = true,
                            NameAr = "ربط المستحق",
                            NameEn = "Entitlement Management — F-0603"
                        },
                        new
                        {
                            PermissionId = 40,
                            CapabilityCode = "CAP-07",
                            FeatureCode = "F-0701",
                            LabelNeedsVerification = true,
                            NameAr = "الإشعارات متعددة",
                            NameEn = "Communication — F-0701"
                        },
                        new
                        {
                            PermissionId = 41,
                            CapabilityCode = "CAP-07",
                            FeatureCode = "F-0702",
                            LabelNeedsVerification = true,
                            NameAr = "إدارة مصفوفة",
                            NameEn = "Communication — F-0702"
                        },
                        new
                        {
                            PermissionId = 42,
                            CapabilityCode = "CAP-07",
                            FeatureCode = "F-0703",
                            LabelNeedsVerification = true,
                            NameAr = "إدارة القوالب",
                            NameEn = "Communication — F-0703"
                        },
                        new
                        {
                            PermissionId = 43,
                            CapabilityCode = "CAP-07",
                            FeatureCode = "F-0704",
                            LabelNeedsVerification = true,
                            NameAr = "شاشة إدارة المهل",
                            NameEn = "Communication — F-0704"
                        },
                        new
                        {
                            PermissionId = 44,
                            CapabilityCode = "CAP-07",
                            FeatureCode = "F-0705",
                            LabelNeedsVerification = true,
                            NameAr = "سجل الإشعارات",
                            NameEn = "Communication — F-0705"
                        },
                        new
                        {
                            PermissionId = 45,
                            CapabilityCode = "CAP-08",
                            FeatureCode = "F-0801",
                            LabelNeedsVerification = true,
                            NameAr = "مصفوفة الصلاحيات",
                            NameEn = "Access & Permissions — F-0801"
                        },
                        new
                        {
                            PermissionId = 46,
                            CapabilityCode = "CAP-08",
                            FeatureCode = "F-0802",
                            LabelNeedsVerification = true,
                            NameAr = "إدارة المستخدمين",
                            NameEn = "Access & Permissions — F-0802"
                        },
                        new
                        {
                            PermissionId = 47,
                            CapabilityCode = "CAP-08",
                            FeatureCode = "F-0805",
                            LabelNeedsVerification = true,
                            NameAr = "سجل التدقيق",
                            NameEn = "Access & Permissions — F-0805"
                        },
                        new
                        {
                            PermissionId = 48,
                            CapabilityCode = "CAP-08",
                            FeatureCode = "F-0806",
                            LabelNeedsVerification = true,
                            NameAr = "إدارة الحساب الذاتي",
                            NameEn = "Access & Permissions — F-0806"
                        },
                        new
                        {
                            PermissionId = 49,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0901",
                            LabelNeedsVerification = true,
                            NameAr = "لوحة مؤشرات",
                            NameEn = "Analytics & Reporting — F-0901"
                        },
                        new
                        {
                            PermissionId = 50,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0902",
                            LabelNeedsVerification = true,
                            NameAr = "لوحة مؤشرات",
                            NameEn = "Analytics & Reporting — F-0902"
                        },
                        new
                        {
                            PermissionId = 51,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0903",
                            LabelNeedsVerification = true,
                            NameAr = "لوحة مؤشرات",
                            NameEn = "Analytics & Reporting — F-0903"
                        },
                        new
                        {
                            PermissionId = 52,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0904",
                            LabelNeedsVerification = true,
                            NameAr = "لوحة الإدارة العليا",
                            NameEn = "Analytics & Reporting — F-0904"
                        },
                        new
                        {
                            PermissionId = 53,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0905",
                            LabelNeedsVerification = true,
                            NameAr = "التقارير الدورية",
                            NameEn = "Analytics & Reporting — F-0905"
                        },
                        new
                        {
                            PermissionId = 54,
                            CapabilityCode = "CAP-09",
                            FeatureCode = "F-0906",
                            LabelNeedsVerification = true,
                            NameAr = "المؤشرات الشخصية",
                            NameEn = "Analytics & Reporting — F-0906"
                        },
                        new
                        {
                            PermissionId = 55,
                            CapabilityCode = "CAP-10",
                            FeatureCode = "F-1001",
                            LabelNeedsVerification = true,
                            NameAr = "صفحة الهبوط",
                            NameEn = "Public Presence — F-1001"
                        },
                        new
                        {
                            PermissionId = 56,
                            CapabilityCode = "CAP-10",
                            FeatureCode = "F-1002",
                            LabelNeedsVerification = true,
                            NameAr = "صفحة دليل المدربين",
                            NameEn = "Public Presence — F-1002"
                        },
                        new
                        {
                            PermissionId = 57,
                            CapabilityCode = "CAP-10",
                            FeatureCode = "F-1003",
                            LabelNeedsVerification = true,
                            NameAr = "موافقة الظهور",
                            NameEn = "Public Presence — F-1003"
                        },
                        new
                        {
                            PermissionId = 58,
                            CapabilityCode = "CAP-10",
                            FeatureCode = "F-1004",
                            LabelNeedsVerification = true,
                            NameAr = "الملف العام",
                            NameEn = "Public Presence — F-1004"
                        });
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.ReferenceList", b =>
                {
                    b.Property<string>("ListCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("list_code");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit")
                        .HasColumnName("is_editable");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_en");

                    b.HasKey("ListCode");

                    b.ToTable("REFERENCE_LIST", (string)null);

                    b.HasData(
                        new
                        {
                            ListCode = "centre",
                            IsEditable = true,
                            NameAr = "المراكز",
                            NameEn = "Centres"
                        });
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.ReferenceValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("value_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("label_ar");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("label_en");

                    b.Property<string>("ListCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("list_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("ValueId");

                    b.HasIndex("ListCode", "Code")
                        .IsUnique();

                    b.ToTable("REFERENCE_VALUE", (string)null);
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description_en");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_en");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ROLE", null, t =>
                        {
                            t.HasCheckConstraint("CK_ROLE_code", "[code] IN ('trainer', 'staff', 'manager', 'centre_coordinator', 'system_administrator', 'executive')");
                        });

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Code = "trainer",
                            DescriptionAr = "يدير ملفه الشخصي، ويتابع طلباته، وإسناداته، ومستحقاته، ويستخدم الخدمات المخصصة له.",
                            DescriptionEn = "Manages their own profile, applications, engagements and entitlements.",
                            IsSystem = true,
                            NameAr = "مدرب",
                            NameEn = "Trainer"
                        },
                        new
                        {
                            RoleId = 2,
                            Code = "staff",
                            DescriptionAr = "ينفذ العمليات التشغيلية اليومية عبر دورة حياة المدرب: الفرز، والتقييم، والاعتماد، وإدارة الملفات، والإسناد، ومتابعة المستحقات.",
                            DescriptionEn = "Runs the daily operations across the trainer lifecycle, per the permissions granted.",
                            IsSystem = true,
                            NameAr = "موظف إدارة المدربين",
                            NameEn = "Trainer Management staff"
                        },
                        new
                        {
                            RoleId = 3,
                            Code = "manager",
                            DescriptionAr = "يشرف على أعمال إدارة المدربين، ويملك جميع صلاحيات الموظف، بالإضافة إلى الاعتماد والقرارات الإشرافية.",
                            DescriptionEn = "Supervises the department; holds every staff permission plus supervisory approvals.",
                            IsSystem = true,
                            NameAr = "مدير إدارة المدربين",
                            NameEn = "Trainer Management manager"
                        },
                        new
                        {
                            RoleId = 4,
                            Code = "centre_coordinator",
                            DescriptionAr = "ينشئ طلبات إسناد المدربين ويتابعها لمركزه، ويراجع حالة الطلبات والتعيينات ضمن نطاق طلبه فقط.",
                            DescriptionEn = "Raises and tracks assignment requests for their own centre, and sees only their own scope.",
                            IsSystem = true,
                            NameAr = "منسق مركز",
                            NameEn = "Centre coordinator"
                        },
                        new
                        {
                            RoleId = 5,
                            Code = "system_administrator",
                            DescriptionAr = "يدير إعدادات المنصة، والأدوار، والصلاحيات، وقوائم التوجيه، والإعدادات التشغيلية.",
                            DescriptionEn = "Manages platform settings, roles, permissions, routing lists and operational configuration.",
                            IsSystem = true,
                            NameAr = "مشرف النظام",
                            NameEn = "System Administrator"
                        },
                        new
                        {
                            RoleId = 6,
                            Code = "executive",
                            DescriptionAr = "تطلع على مؤشرات الأداء والتقارير على مستوى المنصة، بصلاحيات القراءة والتصدير فقط دون تنفيذ أي عمليات تشغيلية.",
                            DescriptionEn = "Reads platform-wide indicators and reports. Read and export only — no operational actions.",
                            IsSystem = true,
                            NameAr = "الإدارة العليا",
                            NameEn = "Senior management"
                        });
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("data_scope");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ROLE_PERMISSION", null, t =>
                        {
                            t.HasCheckConstraint("CK_ROLE_PERMISSION_data_scope", "[data_scope] IN ('all', 'own', 'centre')");
                        });
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("ScopeRef")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scope_ref");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "ScopeRef")
                        .IsUnique();

                    b.ToTable("USER_ROLE", (string)null);
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.Attachment", b =>
                {
                    b.HasOne("ExpertHub.Core.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.AuditLogEntry", b =>
                {
                    b.HasOne("ExpertHub.Core.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.ReferenceValue", b =>
                {
                    b.HasOne("ExpertHub.Core.Domain.ReferenceList", null)
                        .WithMany()
                        .HasForeignKey("ListCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.RolePermission", b =>
                {
                    b.HasOne("ExpertHub.Core.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpertHub.Core.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpertHub.Core.Domain.UserRole", b =>
                {
                    b.HasOne("ExpertHub.Core.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpertHub.Core.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpertHub.Core.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
