// AUTO-GENERATED from the two supplied FAST field files. Do not edit by hand.
//
//   docs/inputs/fast-trainer-profile-fields.xlsx
//   docs/inputs/fast-trainer-history-fields.xlsx
//
// Regenerate after the owner extends either file (the stated intent is that
// they will grow) with the script recorded in `13_FAST_DATA_DICTIONARY_MAP.md`.

/**
 * A snapshot of **exactly what FAST supplied** — nothing inferred, nothing added.
 *
 * This exists so `fastSources.ts` can be *checked* rather than trusted: a claim
 * that some Expert Hub field comes from a FAST column is only meaningful if that
 * column was actually supplied, and `fastSources.test.ts` proves every claim
 * against this snapshot. Inventing a FAST field therefore fails the build.
 *
 * 15 tables · 406 columns · supplied 2026-08-23.
 */
export const FAST_SCHEMA_SNAPSHOT: Readonly<Record<string, readonly string[]>> = {
  // Basic Info
  'dbo.AspNetUsers': [
    'Id',
    'UserName',
    'Email',
    'EmailConfirmed',
    'PhoneNumber',
    'PhoneNumberConfirmed',
    'PreferredCommunicationLanguage',
    'PreferredUiLanguage',
    'FullNameAr',
    'FullNameEn',
    'DateOfBirth',
    'FirstNameAr',
    'MiddleNameAr',
    'ThirdNameAr',
    'LastNameAr',
    'FirstNameEn',
    'MiddleNameEn',
    'ThirdNameEn',
    'LastNameEn',
    'DeactivationReason',
    'IsActive',
    'JobTitle',
    'IsApproved',
    'IsEmployee',
    'UserIDPortal',
    'TraineeIDPortal',
    'UsernamePortal',
    'TrainerIdPortal',
    'LmsUserId',
    'AllowReceiveNewsLetterAndCampaign',
    'LastLoginDate',
    'MTMInstructorRating',
    'MTMInstructorResponceCount',
    'MTMOneRating',
    'MTMTwoRating',
    'MTMThreeRating',
    'MTMFourRating',
    'MTMFiveRating',
  ],
  // Personal & Job Profile
  'profile.UserProfile': [
    'Id',
    'Gender',
    'MaritalStatusId',
    'NationalityCountryId',
    'IdNumber',
    'ResidencyNumber',
    'PassportNumber',
    'GulfIdNumber',
    'OtherOrganization',
    'Address',
    'TelephoneNumber',
    'ProfileImageAttachmentId',
    'SocialMediaUrl',
    'JobTitleAr',
    'JobTitleEn',
    'DepartmentAr',
    'DepartmentEn',
    'JobNumber',
    'CVAttachmentId',
    'NationalIDAttachmentId',
    'ExpertCorrector',
    'ExpertReviewer',
    'ExpertQuestionAuthor',
    'BankAccount',
    'BankName',
    'BankBranch',
    'BankSwiftCode',
    'BankIBAN',
    'AddressAr',
    'AddressEn',
    'IsScanned',
    'IdentityId',
    'IsCollectInDynamics',
    'AddressCityId',
    'AddressCountryId',
    'StudentRequestStatus',
    'StudentApprovAttachmentFileId',
    'BankCountry',
    'BankCity',
    'BankCurrency',
    'IbanAttachmentId',
    'BuildingNumber',
    'Street',
    'District',
    'NationalAddressCity',
    'PostCode',
    'RegionName',
    'NameInBankCard',
    'ObjLatLng',
    'IsPrimaryAddress',
    'UdemyId',
    'Theme',
    'ProfileImagePath',
    'MandatoryExpertDeclaration',
    'OptionalPhotoConsent',
    'CVFileName',
    'CVFilePath',
    'UniversityEmail',
    'UniversityEmailConfirmed',
    'UniversityEmailVerifiedAt',
  ],
  // Education / Qualifications
  'profile.Education': [
    'Id',
    'UserProfileId',
    'QualificationsTypeId',
    'Specialization',
    'DateObtained',
    'Donor',
    'RequestStatus',
    'QualificationAttachmentId',
    'GeneralSpecialization',
  ],
  // Professional Certifications
  'profile.ProfessionalCertification': [
    'Id',
    'UserProfileId',
    'CertificateName',
    'DateObtained',
    'Donor',
    'RequestStatus',
    'ProfessionalCertificationAttachmentId',
    'AttachmentName',
  ],
  // Practical Experience
  'profile.PracticalExperience': [
    'Id',
    'UserProfileId',
    'JobTitle',
    'YearsOfExperience',
    'DateFrom',
    'DateTo',
    'MainTask',
    'Organization',
    'RequestStatus',
    'StillEmployed',
    'IsPartTimeWork',
  ],
  // Training Courses Attended
  'profile.TrainingCourse': [
    'Id',
    'UserProfileId',
    'CourseName',
    'Field',
    'DateTo',
    'DateFrom',
    'NumberOfDays',
    'CourseLevelId',
    'OrganizationName',
    'IsProvided',
    'RequestStatus',
    'TrainingCourseAttachmentId',
    'ProgramId',
    'SectorId',
  ],
  // Training Areas (skills)
  'profile.AreasOfTraining': ['Id', 'UserProfileId', 'FeildId', 'TrainingLevelId'],
  // Cooperation Areas
  'profile.AreasOfCooperation': [
    'Id',
    'UserProfileId',
    'CooperationAreaId',
    'CooperationLanguageId',
    'EventTypeId',
  ],
  // Availability
  'profile.UserAvailabilityWorkingType': [
    'Id',
    'UserProfileId',
    'WorkingTypeId',
    'AvailabilityDuringTheWeekId',
    'AvailabilityDuringDayId',
  ],
  // Trainer ↔ Programme link
  'ImsTraining.plan.PlanTrainer': [
    'Id',
    'PlanId',
    'IsFreelance',
    'TrainerId',
    'MTMInstructorRating',
    'MTMInstructorResponceCount',
    'MTMInstructorOneRating',
    'MTMInstructorTwoRating',
    'MTMInstructorThreeRating',
    'MTMInstructorFourRating',
    'MTMInstructorFiveRating',
    'IsCertificateCreatedForTrainer',
    'CertificateId',
  ],
  // Programme Offering / Session
  'ImsTraining.plan.Plan': [
    'Id',
    'ProgramId',
    'NumberOfDays',
    'NumberOfHours',
    'ProgramFees',
    'IsVatTaxes',
    'MaxPlanTakersNumber',
    'TrainingMaterialLastUpdatedDate',
    'NumberOfSessions',
    'SessionNumberOfHours',
    'HasQuiz',
    'SuccessGrade',
    'IsPublished',
    'PlanStatusId',
    'PlanCancelReasonId',
    'CancelReasonOther',
    'IsFree',
    'TargetGenderId',
    'FoodServicePeriodId',
    'TrainingMaterialStatusId',
    'CoordinatorUserId',
    'ManagerUserId',
    'PlanLocationId',
    'CountryId',
    'CityId',
    'Comments',
    'RoomId',
    'RoomReservationId',
    'ReservationsCount',
    'WeekNumber',
    'PlanIDPortal',
    'FinacialStatus',
    'PurchaseOrderAttachmentId',
    'FinanceCost',
    'Revenue',
    'NetRevenue',
    'TrainingTypeId',
    'Code',
    'LanguageId',
    'ExternalRegistrationURL',
    'IsSponsored',
    'IsForStudent',
    'LmsId',
    'NassejLmsCourseId',
    'IsCollectedInDynamics',
    'IsRegisterationRequireModerator',
    'ProjectId',
    'IdentityId',
    'SendSurveyAfterHours',
    'MtMImportId',
    'IsSurveySent',
    'CanceledBy',
    'CanceledOn',
    'ClosedBy',
    'ClosedOn',
    'FinalClosedBy',
    'FinalClosedOn',
    'TeamsUrl',
    'HotelCost',
    'TrainingSuppliesCost',
    'TrainingPrintMaterialCost',
    'TrainingRolePrintCost',
    'TrainingSunglassesCost',
    'TrainingFlashCost',
    'TrainingTrainerCost',
    'TraineeCost',
    'PartnerAgreementAttachmentId',
    'TrainingMaterialAttachmentId',
    'ExternalLocationId',
    'SupervisorUserId',
    'IsHavePurshedSeats',
    'PONumber',
    'CenterCategoryId',
    'POTrainingTrainerCost',
    'POHotelCost',
    'POTrainingSuppliesCost',
    'POTrainingPrintMaterialCost',
    'IsManuelEnteringTrainingSuppliesCost',
    'IsManuelEnteringTrainingPrintMaterialCost',
    'IsDigitalActivities',
    'MTMClassId',
    'SurveyResponcceRecived',
    'MTMOverAllRating',
    'IsPORetrievedFromDynamic',
    'RelationsManagerUserId',
    'HasPOs',
    'MTMInstructorRating',
    'MTMOneRating',
    'MTMTwoRating',
    'MTMThreeRating',
    'MTMFourRating',
    'MTMFiveRating',
    'MTMResponceCount',
    'StudentPrice',
  ],
  // Session Days (schedule)
  'ImsTraining.plan.PlanScheduleDay': [
    'Id',
    'PlanId',
    'StartDate',
    'EndDate',
    'StartTime',
    'EndTime',
    'IsLatestSchedule',
    'IsDaysRequireSpecificTimes',
  ],
  // Programme
  'ImsTraining.program.Program': [
    'Id',
    'NameAr',
    'NameEn',
    'ProgramLevelId',
    'LanguageId',
    'ProgramTypeId',
    'TrainingTypeId',
    'CompetencyId',
    'PerformanceCriteriaId',
    'TrackInductionId',
    'MaxPlanTakersNumber',
    'NumberOfDays',
    'NumberOfHours',
    'TrainigStyleDescriptionAr',
    'TrainigStyleDescriptionEn',
    'TrainingMaterialAttachmentId',
    'TrainingMaterialLastUpdatedDate',
    'BriefAr',
    'BriefEn',
    'IsPublished',
    'VersionNum',
    'VersioningRelatedCode',
    'IsLastVersion',
    'IsOriginalVersion',
    'CustomProgramRequestId',
    'ImageAttachmentId',
    'IsApplyDiscountGroups',
    'ProgramFees',
    'CompetencyLevelId',
    'UnPublishedReasons',
    'IsCustomProgram',
    'CustomDiscountPercentage',
    'FeesBeforeDiscount',
    'CourseIDPortal',
    'YearIDPortal',
    'ProgramIDPortal',
    'ProgramStatusId',
    'CertificateDisplayNameAr',
    'CertificateDisplayNameEn',
    'ShowPartners',
    'IsCollectInDynamics',
    'ProgramPurposeId',
    'Code',
    'ExternalRegistrationURL',
    'IsForStudent',
    'PackageId',
    'ProgramTopicId',
    'AutomationPriceOnline',
    'AutomationPriceInClass',
    'ProspectusAttachmentId',
    'LearnerJourneyAttachmentId',
    'IsPublishedForOrganizations',
    'UnPublishedForOrganizationsReasons',
    'AllowedPeriodPerDayForNextReservation',
    'CenterCategoryId',
    'IsNafath',
    'ProgramParticipantLevelId',
    'ProgramSkillTypeId',
    'ProspectusAttachmentEnId',
    'BrochureAttachmentArId',
    'BrochureAttachmentEnId',
    'VideoURL',
    'EnableBundleFeature',
    'ShowOldPlans',
    'IsTrending',
    'UserRate',
    'MarketingDescriptionAr',
    'MarketingDescriptionEn',
    'EducationalDescriptionAr',
    'EducationalDescriptionEn',
    'AcceptanceDescriptionAr',
    'AcceptanceDescriptionEn',
    'AcceptanceRequirementsDescriptionAr',
    'AcceptanceRequirementsDescriptionEn',
    'FutureInvestmentDescriptionAr',
    'FutureInvestmentDescriptionEn',
    'OrganizationBenefitsDescriptionAr',
    'OrganizationBenefitsDescriptionEn',
    'ProfessionalDevelopmentDescriptionAr',
    'ProfessionalDevelopmentDescriptionEn',
    'StatisticsDescriptionAr',
    'StatisticsDescriptionEn',
    'PromotionMediaId',
    'PromotionMediaLinkAr',
    'PromotionMediaLinkEn',
    'InitialUsersRate',
    'InitialUsersRateUsersCount',
    'ThumbnailImageAttachmentId',
    'ExamId',
    'NumberOfFreeRetry',
    'DaysForTakeFreeExamValidity',
    'IsExecutive',
    'SearchKeywords',
    'IsHideExecutiveFromPortal',
    'HasRelatedProgram',
    'NumberOfMinutes',
    'ProgramSponsorTextAr',
    'ProgramSponsorTextEn',
    'ImageAltAr',
    'ImageAltEn',
    'ImageTitleAr',
    'ImageTitleEn',
    'NumberOfUserRates',
    'ApplicationProcessTitleAr',
    'ApplicationProcessTitleEn',
    'ApplicationProcessDescriptionAr',
    'ApplicationProcessDescriptionEn',
    'AcceptanceTitleAr',
    'AcceptanceTitleEn',
    'IsHrdfSupported',
    'IsForStudentsAndGeneral',
  ],
  // Evaluation - Instructor record
  'ImsCommon.Survey.Instructor': [
    'InstructorID',
    'InstructorFirstName',
    'InstructorLastName',
    'ExternalInstructorID',
    'InstructorEmail',
    'CertificationDetails',
    'IsActive',
    'LastModifiedDate',
    'UserId',
  ],
  // Evaluation - Survey response
  'ImsCommon.Survey.SurveyResponse': [
    'AnswerID',
    'EvalSubmittedID',
    'EnrollmentID',
    'ResponderIdentifier',
    'AnswerType',
    'AnswerData',
    'EnteredDateTime',
    'QuestionID',
    'ClassID',
    'EventID',
    'FormID',
    'ScaleHigh',
    'ScaleLow',
    'ReportingDate',
    'InstructorID',
    'LastModifiedDate',
    'IsSentToUserRate',
  ],
};

/** Every `Table.Column` the files supplied, as one flat set for lookups. */
export const FAST_COLUMNS: ReadonlySet<string> = new Set(
  Object.entries(FAST_SCHEMA_SNAPSHOT).flatMap(([table, columns]) =>
    columns.map((column) => `${table}.${column}`)
  )
);
