// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/ to regenerate. The Icon component's public API
// (Icon.tsx) never needs to change when this file changes.
//
// This file only aggregates the per-category registries under ./registry/
// — it never imports SVGs directly, so adding a category only touches
// that category's own registry file plus the two lines this generator
// appends here.
import { addRemoveIcons } from './registry/add-remove';
import { alertIcons } from './registry/alert';
import { communityIconsIcons } from './registry/community-icons';
import { dashboardIcons } from './registry/dashboard';
import { downloadUploadIcons } from './registry/download-upload';
import { gitIcons } from './registry/git';
import { homeIcons } from './registry/home';
import { loginLogoutIcons } from './registry/login-logout';
import { notesTasksIcons } from './registry/notes-tasks';
import { presentationIcons } from './registry/presentation';
import { scienceTechnologyIcons } from './registry/science-technology';
import { searchIcons } from './registry/search';
import { shapesIcons } from './registry/shapes';

export const iconRegistry = {
  ...addRemoveIcons,
  ...alertIcons,
  ...communityIconsIcons,
  ...dashboardIcons,
  ...downloadUploadIcons,
  ...gitIcons,
  ...homeIcons,
  ...loginLogoutIcons,
  ...notesTasksIcons,
  ...presentationIcons,
  ...scienceTechnologyIcons,
  ...searchIcons,
  ...shapesIcons,
} as const;

export type IconName = keyof typeof iconRegistry;
