// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/add-remove/ to regenerate this category's registry.
import icon_add_01 from '@/assets/icons/add-remove/add-01.svg?raw';
import icon_add_02 from '@/assets/icons/add-remove/add-02.svg?raw';
import icon_add_circle from '@/assets/icons/add-remove/add-circle.svg?raw';
import icon_add_circle_half_dot from '@/assets/icons/add-remove/add-circle-half-dot.svg?raw';
import icon_add_square from '@/assets/icons/add-remove/add-square.svg?raw';
import icon_cancel_01 from '@/assets/icons/add-remove/cancel-01.svg?raw';
import icon_cancel_02 from '@/assets/icons/add-remove/cancel-02.svg?raw';
import icon_cancel_circle from '@/assets/icons/add-remove/cancel-circle.svg?raw';
import icon_cancel_circle_half_dot from '@/assets/icons/add-remove/cancel-circle-half-dot.svg?raw';
import icon_cancel_square from '@/assets/icons/add-remove/cancel-square.svg?raw';
import icon_delete_01 from '@/assets/icons/add-remove/delete-01.svg?raw';
import icon_delete_02 from '@/assets/icons/add-remove/delete-02.svg?raw';
import icon_delete_03 from '@/assets/icons/add-remove/delete-03.svg?raw';
import icon_delete_04 from '@/assets/icons/add-remove/delete-04.svg?raw';
import icon_delete_put_back from '@/assets/icons/add-remove/delete-put-back.svg?raw';
import icon_delete_throw from '@/assets/icons/add-remove/delete-throw.svg?raw';
import icon_eraser_01 from '@/assets/icons/add-remove/eraser-01.svg?raw';
import icon_eraser_add from '@/assets/icons/add-remove/eraser-add.svg?raw';
import icon_remove_01 from '@/assets/icons/add-remove/remove-01.svg?raw';
import icon_remove_02 from '@/assets/icons/add-remove/remove-02.svg?raw';
import icon_remove_circle from '@/assets/icons/add-remove/remove-circle.svg?raw';
import icon_remove_circle_half_dot from '@/assets/icons/add-remove/remove-circle-half-dot.svg?raw';
import icon_remove_square from '@/assets/icons/add-remove/remove-square.svg?raw';
import icon_restore_bin from '@/assets/icons/add-remove/restore-bin.svg?raw';
import icon_unavailable from '@/assets/icons/add-remove/unavailable.svg?raw';
import icon_waste from '@/assets/icons/add-remove/waste.svg?raw';
import icon_waste_restore from '@/assets/icons/add-remove/waste-restore.svg?raw';

export const addRemoveIcons = {
  'add-01': icon_add_01,
  'add-02': icon_add_02,
  'add-circle': icon_add_circle,
  'add-circle-half-dot': icon_add_circle_half_dot,
  'add-square': icon_add_square,
  'cancel-01': icon_cancel_01,
  'cancel-02': icon_cancel_02,
  'cancel-circle': icon_cancel_circle,
  'cancel-circle-half-dot': icon_cancel_circle_half_dot,
  'cancel-square': icon_cancel_square,
  'delete-01': icon_delete_01,
  'delete-02': icon_delete_02,
  'delete-03': icon_delete_03,
  'delete-04': icon_delete_04,
  'delete-put-back': icon_delete_put_back,
  'delete-throw': icon_delete_throw,
  'eraser-01': icon_eraser_01,
  'eraser-add': icon_eraser_add,
  'remove-01': icon_remove_01,
  'remove-02': icon_remove_02,
  'remove-circle': icon_remove_circle,
  'remove-circle-half-dot': icon_remove_circle_half_dot,
  'remove-square': icon_remove_square,
  'restore-bin': icon_restore_bin,
  unavailable: icon_unavailable,
  waste: icon_waste,
  'waste-restore': icon_waste_restore,
} as const;
