// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/alert/ to regenerate this category's registry.
import icon_alert_01 from '@/assets/icons/alert/alert-01.svg?raw';
import icon_alert_02 from '@/assets/icons/alert/alert-02.svg?raw';
import icon_alert_circle from '@/assets/icons/alert/alert-circle.svg?raw';
import icon_alert_diamond from '@/assets/icons/alert/alert-diamond.svg?raw';
import icon_alert_square from '@/assets/icons/alert/alert-square.svg?raw';
import icon_help_circle from '@/assets/icons/alert/help-circle.svg?raw';
import icon_help_square from '@/assets/icons/alert/help-square.svg?raw';
import icon_information_circle from '@/assets/icons/alert/information-circle.svg?raw';
import icon_information_diamond from '@/assets/icons/alert/information-diamond.svg?raw';
import icon_information_square from '@/assets/icons/alert/information-square.svg?raw';
import icon_notification_01 from '@/assets/icons/alert/notification-01.svg?raw';
import icon_notification_02 from '@/assets/icons/alert/notification-02.svg?raw';
import icon_notification_03 from '@/assets/icons/alert/notification-03.svg?raw';
import icon_notification_block_01 from '@/assets/icons/alert/notification-block-01.svg?raw';
import icon_notification_block_02 from '@/assets/icons/alert/notification-block-02.svg?raw';
import icon_notification_block_03 from '@/assets/icons/alert/notification-block-03.svg?raw';
import icon_notification_bubble from '@/assets/icons/alert/notification-bubble.svg?raw';
import icon_notification_circle from '@/assets/icons/alert/notification-circle.svg?raw';
import icon_notification_off_01 from '@/assets/icons/alert/notification-off-01.svg?raw';
import icon_notification_off_02 from '@/assets/icons/alert/notification-off-02.svg?raw';
import icon_notification_off_03 from '@/assets/icons/alert/notification-off-03.svg?raw';
import icon_notification_snooze_01 from '@/assets/icons/alert/notification-snooze-01.svg?raw';
import icon_notification_snooze_02 from '@/assets/icons/alert/notification-snooze-02.svg?raw';
import icon_notification_snooze_03 from '@/assets/icons/alert/notification-snooze-03.svg?raw';
import icon_notification_square from '@/assets/icons/alert/notification-square.svg?raw';
import icon_radioactive_alert from '@/assets/icons/alert/radioactive-alert.svg?raw';
import icon_spam from '@/assets/icons/alert/spam.svg?raw';

export const alertIcons = {
  'alert-01': icon_alert_01,
  'alert-02': icon_alert_02,
  'alert-circle': icon_alert_circle,
  'alert-diamond': icon_alert_diamond,
  'alert-square': icon_alert_square,
  'help-circle': icon_help_circle,
  'help-square': icon_help_square,
  'information-circle': icon_information_circle,
  'information-diamond': icon_information_diamond,
  'information-square': icon_information_square,
  'notification-01': icon_notification_01,
  'notification-02': icon_notification_02,
  'notification-03': icon_notification_03,
  'notification-block-01': icon_notification_block_01,
  'notification-block-02': icon_notification_block_02,
  'notification-block-03': icon_notification_block_03,
  'notification-bubble': icon_notification_bubble,
  'notification-circle': icon_notification_circle,
  'notification-off-01': icon_notification_off_01,
  'notification-off-02': icon_notification_off_02,
  'notification-off-03': icon_notification_off_03,
  'notification-snooze-01': icon_notification_snooze_01,
  'notification-snooze-02': icon_notification_snooze_02,
  'notification-snooze-03': icon_notification_snooze_03,
  'notification-square': icon_notification_square,
  'radioactive-alert': icon_radioactive_alert,
  spam: icon_spam,
} as const;
