// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/community-icons/ to regenerate this category's registry.
import icon_give_star from '@/assets/icons/community-icons/give-star.svg?raw';
import icon_petals_01 from '@/assets/icons/community-icons/petals-01.svg?raw';
import icon_petals_02 from '@/assets/icons/community-icons/petals-02.svg?raw';
import icon_petals_03 from '@/assets/icons/community-icons/petals-03.svg?raw';
import icon_sheep_01 from '@/assets/icons/community-icons/sheep-01.svg?raw';
import icon_sprout_01 from '@/assets/icons/community-icons/sprout-01.svg?raw';
import icon_sprout_02 from '@/assets/icons/community-icons/sprout-02.svg?raw';
import icon_zakat_bag_closed from '@/assets/icons/community-icons/zakat-bag-closed.svg?raw';
import icon_zakat_bag_open from '@/assets/icons/community-icons/zakat-bag-open.svg?raw';

export const communityIconsIcons = {
  'give-star': icon_give_star,
  'petals-01': icon_petals_01,
  'petals-02': icon_petals_02,
  'petals-03': icon_petals_03,
  'sheep-01': icon_sheep_01,
  'sprout-01': icon_sprout_01,
  'sprout-02': icon_sprout_02,
  'zakat-bag-closed': icon_zakat_bag_closed,
  'zakat-bag-open': icon_zakat_bag_open,
} as const;
