// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/dashboard/ to regenerate this category's registry.
import icon_dashboard_browsing from '@/assets/icons/dashboard/dashboard-browsing.svg?raw';
import icon_dashboard_circle from '@/assets/icons/dashboard/dashboard-circle.svg?raw';
import icon_dashboard_circle_add from '@/assets/icons/dashboard/dashboard-circle-add.svg?raw';
import icon_dashboard_circle_edit from '@/assets/icons/dashboard/dashboard-circle-edit.svg?raw';
import icon_dashboard_circle_remove from '@/assets/icons/dashboard/dashboard-circle-remove.svg?raw';
import icon_dashboard_circle_settings from '@/assets/icons/dashboard/dashboard-circle-settings.svg?raw';
import icon_dashboard_speed_01 from '@/assets/icons/dashboard/dashboard-speed-01.svg?raw';
import icon_dashboard_speed_02 from '@/assets/icons/dashboard/dashboard-speed-02.svg?raw';
import icon_dashboard_square_01 from '@/assets/icons/dashboard/dashboard-square-01.svg?raw';
import icon_dashboard_square_02 from '@/assets/icons/dashboard/dashboard-square-02.svg?raw';
import icon_dashboard_square_03 from '@/assets/icons/dashboard/dashboard-square-03.svg?raw';
import icon_dashboard_square_add from '@/assets/icons/dashboard/dashboard-square-add.svg?raw';
import icon_dashboard_square_edit from '@/assets/icons/dashboard/dashboard-square-edit.svg?raw';
import icon_dashboard_square_remove from '@/assets/icons/dashboard/dashboard-square-remove.svg?raw';
import icon_dashboard_square_setting from '@/assets/icons/dashboard/dashboard-square-setting.svg?raw';
import icon_discover_circle from '@/assets/icons/dashboard/discover-circle.svg?raw';
import icon_discover_square from '@/assets/icons/dashboard/discover-square.svg?raw';
import icon_sidebar_bottom from '@/assets/icons/dashboard/sidebar-bottom.svg?raw';
import icon_sidebar_left from '@/assets/icons/dashboard/sidebar-left.svg?raw';
import icon_sidebar_right from '@/assets/icons/dashboard/sidebar-right.svg?raw';
import icon_sidebar_top from '@/assets/icons/dashboard/sidebar-top.svg?raw';

export const dashboardIcons = {
  'dashboard-browsing': icon_dashboard_browsing,
  'dashboard-circle': icon_dashboard_circle,
  'dashboard-circle-add': icon_dashboard_circle_add,
  'dashboard-circle-edit': icon_dashboard_circle_edit,
  'dashboard-circle-remove': icon_dashboard_circle_remove,
  'dashboard-circle-settings': icon_dashboard_circle_settings,
  'dashboard-speed-01': icon_dashboard_speed_01,
  'dashboard-speed-02': icon_dashboard_speed_02,
  'dashboard-square-01': icon_dashboard_square_01,
  'dashboard-square-02': icon_dashboard_square_02,
  'dashboard-square-03': icon_dashboard_square_03,
  'dashboard-square-add': icon_dashboard_square_add,
  'dashboard-square-edit': icon_dashboard_square_edit,
  'dashboard-square-remove': icon_dashboard_square_remove,
  'dashboard-square-setting': icon_dashboard_square_setting,
  'discover-circle': icon_discover_circle,
  'discover-square': icon_discover_square,
  'sidebar-bottom': icon_sidebar_bottom,
  'sidebar-left': icon_sidebar_left,
  'sidebar-right': icon_sidebar_right,
  'sidebar-top': icon_sidebar_top,
} as const;
