// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/download-upload/ to regenerate this category's registry.
import icon_cloud_download from '@/assets/icons/download-upload/cloud-download.svg?raw';
import icon_cloud_upload from '@/assets/icons/download-upload/cloud-upload.svg?raw';
import icon_download_01 from '@/assets/icons/download-upload/download-01.svg?raw';
import icon_download_02 from '@/assets/icons/download-upload/download-02.svg?raw';
import icon_download_03 from '@/assets/icons/download-upload/download-03.svg?raw';
import icon_download_04 from '@/assets/icons/download-upload/download-04.svg?raw';
import icon_download_05 from '@/assets/icons/download-upload/download-05.svg?raw';
import icon_download_circle_01 from '@/assets/icons/download-upload/download-circle-01.svg?raw';
import icon_download_circle_02 from '@/assets/icons/download-upload/download-circle-02.svg?raw';
import icon_download_square_01 from '@/assets/icons/download-upload/download-square-01.svg?raw';
import icon_download_square_02 from '@/assets/icons/download-upload/download-square-02.svg?raw';
import icon_upload_01 from '@/assets/icons/download-upload/upload-01.svg?raw';
import icon_upload_02 from '@/assets/icons/download-upload/upload-02.svg?raw';
import icon_upload_03 from '@/assets/icons/download-upload/upload-03.svg?raw';
import icon_upload_04 from '@/assets/icons/download-upload/upload-04.svg?raw';
import icon_upload_05 from '@/assets/icons/download-upload/upload-05.svg?raw';
import icon_upload_circle_01 from '@/assets/icons/download-upload/upload-circle-01.svg?raw';
import icon_upload_circle_02 from '@/assets/icons/download-upload/upload-circle-02.svg?raw';
import icon_upload_square_01 from '@/assets/icons/download-upload/upload-square-01.svg?raw';
import icon_upload_square_02 from '@/assets/icons/download-upload/upload-square-02.svg?raw';

export const downloadUploadIcons = {
  'cloud-download': icon_cloud_download,
  'cloud-upload': icon_cloud_upload,
  'download-01': icon_download_01,
  'download-02': icon_download_02,
  'download-03': icon_download_03,
  'download-04': icon_download_04,
  'download-05': icon_download_05,
  'download-circle-01': icon_download_circle_01,
  'download-circle-02': icon_download_circle_02,
  'download-square-01': icon_download_square_01,
  'download-square-02': icon_download_square_02,
  'upload-01': icon_upload_01,
  'upload-02': icon_upload_02,
  'upload-03': icon_upload_03,
  'upload-04': icon_upload_04,
  'upload-05': icon_upload_05,
  'upload-circle-01': icon_upload_circle_01,
  'upload-circle-02': icon_upload_circle_02,
  'upload-square-01': icon_upload_square_01,
  'upload-square-02': icon_upload_square_02,
} as const;
