// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/git/ to regenerate this category's registry.
import icon_git_branch from '@/assets/icons/git/git-branch.svg?raw';
import icon_git_commit from '@/assets/icons/git/git-commit.svg?raw';
import icon_git_compare from '@/assets/icons/git/git-compare.svg?raw';
import icon_git_fork from '@/assets/icons/git/git-fork.svg?raw';
import icon_git_merge from '@/assets/icons/git/git-merge.svg?raw';
import icon_git_pull_request from '@/assets/icons/git/git-pull-request.svg?raw';
import icon_git_pull_request_closed from '@/assets/icons/git/git-pull-request-closed.svg?raw';
import icon_git_pull_request_draft from '@/assets/icons/git/git-pull-request-draft.svg?raw';
import icon_github from '@/assets/icons/git/github.svg?raw';
import icon_gitlab from '@/assets/icons/git/gitlab.svg?raw';

export const gitIcons = {
  'git-branch': icon_git_branch,
  'git-commit': icon_git_commit,
  'git-compare': icon_git_compare,
  'git-fork': icon_git_fork,
  'git-merge': icon_git_merge,
  'git-pull-request': icon_git_pull_request,
  'git-pull-request-closed': icon_git_pull_request_closed,
  'git-pull-request-draft': icon_git_pull_request_draft,
  github: icon_github,
  gitlab: icon_gitlab,
} as const;
