// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/home/ to regenerate this category's registry.
import icon_door_01 from '@/assets/icons/home/door-01.svg?raw';
import icon_door_02 from '@/assets/icons/home/door-02.svg?raw';
import icon_home_01 from '@/assets/icons/home/home-01.svg?raw';
import icon_home_02 from '@/assets/icons/home/home-02.svg?raw';
import icon_home_03 from '@/assets/icons/home/home-03.svg?raw';
import icon_home_04 from '@/assets/icons/home/home-04.svg?raw';
import icon_home_05 from '@/assets/icons/home/home-05.svg?raw';
import icon_home_06 from '@/assets/icons/home/home-06.svg?raw';
import icon_home_07 from '@/assets/icons/home/home-07.svg?raw';
import icon_home_08 from '@/assets/icons/home/home-08.svg?raw';
import icon_home_09 from '@/assets/icons/home/home-09.svg?raw';
import icon_home_10 from '@/assets/icons/home/home-10.svg?raw';
import icon_home_11 from '@/assets/icons/home/home-11.svg?raw';
import icon_home_12 from '@/assets/icons/home/home-12.svg?raw';
import icon_home_13 from '@/assets/icons/home/home-13.svg?raw';

export const homeIcons = {
  'door-01': icon_door_01,
  'door-02': icon_door_02,
  'home-01': icon_home_01,
  'home-02': icon_home_02,
  'home-03': icon_home_03,
  'home-04': icon_home_04,
  'home-05': icon_home_05,
  'home-06': icon_home_06,
  'home-07': icon_home_07,
  'home-08': icon_home_08,
  'home-09': icon_home_09,
  'home-10': icon_home_10,
  'home-11': icon_home_11,
  'home-12': icon_home_12,
  'home-13': icon_home_13,
} as const;
