// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/login-logout/ to regenerate this category's registry.
import icon_login_01 from '@/assets/icons/login-logout/login-01.svg?raw';
import icon_login_02 from '@/assets/icons/login-logout/login-02.svg?raw';
import icon_login_03 from '@/assets/icons/login-logout/login-03.svg?raw';
import icon_login_circle_01 from '@/assets/icons/login-logout/login-circle-01.svg?raw';
import icon_login_circle_02 from '@/assets/icons/login-logout/login-circle-02.svg?raw';
import icon_login_square_01 from '@/assets/icons/login-logout/login-square-01.svg?raw';
import icon_login_square_02 from '@/assets/icons/login-logout/login-square-02.svg?raw';
import icon_logout_01 from '@/assets/icons/login-logout/logout-01.svg?raw';
import icon_logout_02 from '@/assets/icons/login-logout/logout-02.svg?raw';
import icon_logout_03 from '@/assets/icons/login-logout/logout-03.svg?raw';
import icon_logout_04 from '@/assets/icons/login-logout/logout-04.svg?raw';
import icon_logout_05 from '@/assets/icons/login-logout/logout-05.svg?raw';
import icon_logout_circle_01 from '@/assets/icons/login-logout/logout-circle-01.svg?raw';
import icon_logout_circle_02 from '@/assets/icons/login-logout/logout-circle-02.svg?raw';
import icon_logout_square_01 from '@/assets/icons/login-logout/logout-square-01.svg?raw';
import icon_logout_square_02 from '@/assets/icons/login-logout/logout-square-02.svg?raw';

export const loginLogoutIcons = {
  'login-01': icon_login_01,
  'login-02': icon_login_02,
  'login-03': icon_login_03,
  'login-circle-01': icon_login_circle_01,
  'login-circle-02': icon_login_circle_02,
  'login-square-01': icon_login_square_01,
  'login-square-02': icon_login_square_02,
  'logout-01': icon_logout_01,
  'logout-02': icon_logout_02,
  'logout-03': icon_logout_03,
  'logout-04': icon_logout_04,
  'logout-05': icon_logout_05,
  'logout-circle-01': icon_logout_circle_01,
  'logout-circle-02': icon_logout_circle_02,
  'logout-square-01': icon_logout_square_01,
  'logout-square-02': icon_logout_square_02,
} as const;
