// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/notes-tasks/ to regenerate this category's registry.
import icon_add_to_list from '@/assets/icons/notes-tasks/add-to-list.svg?raw';
import icon_note_01 from '@/assets/icons/notes-tasks/note-01.svg?raw';
import icon_note_02 from '@/assets/icons/notes-tasks/note-02.svg?raw';
import icon_note_03 from '@/assets/icons/notes-tasks/note-03.svg?raw';
import icon_note_04 from '@/assets/icons/notes-tasks/note-04.svg?raw';
import icon_note_05 from '@/assets/icons/notes-tasks/note-05.svg?raw';
import icon_note_add from '@/assets/icons/notes-tasks/note-add.svg?raw';
import icon_note_done from '@/assets/icons/notes-tasks/note-done.svg?raw';
import icon_note_edit from '@/assets/icons/notes-tasks/note-edit.svg?raw';
import icon_note_remove from '@/assets/icons/notes-tasks/note-remove.svg?raw';
import icon_notebook from '@/assets/icons/notes-tasks/notebook.svg?raw';
import icon_sticky_note_01 from '@/assets/icons/notes-tasks/sticky-note-01.svg?raw';
import icon_sticky_note_02 from '@/assets/icons/notes-tasks/sticky-note-02.svg?raw';
import icon_task_01 from '@/assets/icons/notes-tasks/task-01.svg?raw';
import icon_task_02 from '@/assets/icons/notes-tasks/task-02.svg?raw';
import icon_task_add_01 from '@/assets/icons/notes-tasks/task-add-01.svg?raw';
import icon_task_add_02 from '@/assets/icons/notes-tasks/task-add-02.svg?raw';
import icon_task_daily_01 from '@/assets/icons/notes-tasks/task-daily-01.svg?raw';
import icon_task_daily_02 from '@/assets/icons/notes-tasks/task-daily-02.svg?raw';
import icon_task_done_01 from '@/assets/icons/notes-tasks/task-done-01.svg?raw';
import icon_task_done_02 from '@/assets/icons/notes-tasks/task-done-02.svg?raw';
import icon_task_edit_01 from '@/assets/icons/notes-tasks/task-edit-01.svg?raw';
import icon_task_edit_02 from '@/assets/icons/notes-tasks/task-edit-02.svg?raw';
import icon_task_remove_01 from '@/assets/icons/notes-tasks/task-remove-01.svg?raw';
import icon_task_remove_02 from '@/assets/icons/notes-tasks/task-remove-02.svg?raw';

export const notesTasksIcons = {
  'add-to-list': icon_add_to_list,
  'note-01': icon_note_01,
  'note-02': icon_note_02,
  'note-03': icon_note_03,
  'note-04': icon_note_04,
  'note-05': icon_note_05,
  'note-add': icon_note_add,
  'note-done': icon_note_done,
  'note-edit': icon_note_edit,
  'note-remove': icon_note_remove,
  notebook: icon_notebook,
  'sticky-note-01': icon_sticky_note_01,
  'sticky-note-02': icon_sticky_note_02,
  'task-01': icon_task_01,
  'task-02': icon_task_02,
  'task-add-01': icon_task_add_01,
  'task-add-02': icon_task_add_02,
  'task-daily-01': icon_task_daily_01,
  'task-daily-02': icon_task_daily_02,
  'task-done-01': icon_task_done_01,
  'task-done-02': icon_task_done_02,
  'task-edit-01': icon_task_edit_01,
  'task-edit-02': icon_task_edit_02,
  'task-remove-01': icon_task_remove_01,
  'task-remove-02': icon_task_remove_02,
} as const;
