// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/presentation/ to regenerate this category's registry.
import icon_co_present from '@/assets/icons/presentation/co-present.svg?raw';
import icon_presentation_01 from '@/assets/icons/presentation/presentation-01.svg?raw';
import icon_presentation_02 from '@/assets/icons/presentation/presentation-02.svg?raw';
import icon_presentation_03 from '@/assets/icons/presentation/presentation-03.svg?raw';
import icon_presentation_04 from '@/assets/icons/presentation/presentation-04.svg?raw';
import icon_presentation_05 from '@/assets/icons/presentation/presentation-05.svg?raw';
import icon_presentation_06 from '@/assets/icons/presentation/presentation-06.svg?raw';
import icon_presentation_07 from '@/assets/icons/presentation/presentation-07.svg?raw';
import icon_presentation_bar_chart_01 from '@/assets/icons/presentation/presentation-bar-chart-01.svg?raw';
import icon_presentation_bar_chart_02 from '@/assets/icons/presentation/presentation-bar-chart-02.svg?raw';
import icon_presentation_line_chart_01 from '@/assets/icons/presentation/presentation-line-chart-01.svg?raw';
import icon_presentation_line_chart_02 from '@/assets/icons/presentation/presentation-line-chart-02.svg?raw';
import icon_presentation_online from '@/assets/icons/presentation/presentation-online.svg?raw';
import icon_presentation_podium from '@/assets/icons/presentation/presentation-podium.svg?raw';
import icon_projector_01 from '@/assets/icons/presentation/projector-01.svg?raw';

export const presentationIcons = {
  'co-present': icon_co_present,
  'presentation-01': icon_presentation_01,
  'presentation-02': icon_presentation_02,
  'presentation-03': icon_presentation_03,
  'presentation-04': icon_presentation_04,
  'presentation-05': icon_presentation_05,
  'presentation-06': icon_presentation_06,
  'presentation-07': icon_presentation_07,
  'presentation-bar-chart-01': icon_presentation_bar_chart_01,
  'presentation-bar-chart-02': icon_presentation_bar_chart_02,
  'presentation-line-chart-01': icon_presentation_line_chart_01,
  'presentation-line-chart-02': icon_presentation_line_chart_02,
  'presentation-online': icon_presentation_online,
  'presentation-podium': icon_presentation_podium,
  'projector-01': icon_projector_01,
} as const;
