// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/science-technology/ to regenerate this category's registry.
import icon_acceleration from '@/assets/icons/science-technology/acceleration.svg?raw';
import icon_atom_01 from '@/assets/icons/science-technology/atom-01.svg?raw';
import icon_atom_02 from '@/assets/icons/science-technology/atom-02.svg?raw';
import icon_bacteria from '@/assets/icons/science-technology/bacteria.svg?raw';
import icon_black_hole_01 from '@/assets/icons/science-technology/black-hole-01.svg?raw';
import icon_bot from '@/assets/icons/science-technology/bot.svg?raw';
import icon_bounding_box from '@/assets/icons/science-technology/bounding-box.svg?raw';
import icon_cells from '@/assets/icons/science-technology/cells.svg?raw';
import icon_gravity from '@/assets/icons/science-technology/gravity.svg?raw';
import icon_magnet from '@/assets/icons/science-technology/magnet.svg?raw';
import icon_molecules from '@/assets/icons/science-technology/molecules.svg?raw';
import icon_nano_technology from '@/assets/icons/science-technology/nano-technology.svg?raw';
import icon_pendulum from '@/assets/icons/science-technology/pendulum.svg?raw';
import icon_prism_01 from '@/assets/icons/science-technology/prism-01.svg?raw';
import icon_pulley from '@/assets/icons/science-technology/pulley.svg?raw';
import icon_siri from '@/assets/icons/science-technology/siri.svg?raw';
import icon_solar_system_01 from '@/assets/icons/science-technology/solar-system-01.svg?raw';
import icon_submerge from '@/assets/icons/science-technology/submerge.svg?raw';
import icon_test_tube from '@/assets/icons/science-technology/test-tube.svg?raw';
import icon_triangle_03 from '@/assets/icons/science-technology/triangle-03.svg?raw';
import icon_ufo_01 from '@/assets/icons/science-technology/ufo-01.svg?raw';
import icon_wind_turbine from '@/assets/icons/science-technology/wind-turbine.svg?raw';

export const scienceTechnologyIcons = {
  acceleration: icon_acceleration,
  'atom-01': icon_atom_01,
  'atom-02': icon_atom_02,
  bacteria: icon_bacteria,
  'black-hole-01': icon_black_hole_01,
  bot: icon_bot,
  'bounding-box': icon_bounding_box,
  cells: icon_cells,
  gravity: icon_gravity,
  magnet: icon_magnet,
  molecules: icon_molecules,
  'nano-technology': icon_nano_technology,
  pendulum: icon_pendulum,
  'prism-01': icon_prism_01,
  pulley: icon_pulley,
  siri: icon_siri,
  'solar-system-01': icon_solar_system_01,
  submerge: icon_submerge,
  'test-tube': icon_test_tube,
  'triangle-03': icon_triangle_03,
  'ufo-01': icon_ufo_01,
  'wind-turbine': icon_wind_turbine,
} as const;
