// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/search/ to regenerate this category's registry.
import icon_search_01 from '@/assets/icons/search/search-01.svg?raw';
import icon_search_02 from '@/assets/icons/search/search-02.svg?raw';
import icon_search_add from '@/assets/icons/search/search-add.svg?raw';
import icon_search_area from '@/assets/icons/search/search-area.svg?raw';
import icon_search_circle from '@/assets/icons/search/search-circle.svg?raw';
import icon_search_focus from '@/assets/icons/search/search-focus.svg?raw';
import icon_search_list_01 from '@/assets/icons/search/search-list-01.svg?raw';
import icon_search_list_02 from '@/assets/icons/search/search-list-02.svg?raw';
import icon_search_minus from '@/assets/icons/search/search-minus.svg?raw';
import icon_search_remove from '@/assets/icons/search/search-remove.svg?raw';
import icon_search_square from '@/assets/icons/search/search-square.svg?raw';
import icon_search_visual from '@/assets/icons/search/search-visual.svg?raw';
import icon_searching from '@/assets/icons/search/searching.svg?raw';
import icon_zoom_in_area from '@/assets/icons/search/zoom-in-area.svg?raw';
import icon_zoom_out_area from '@/assets/icons/search/zoom-out-area.svg?raw';

export const searchIcons = {
  'search-01': icon_search_01,
  'search-02': icon_search_02,
  'search-add': icon_search_add,
  'search-area': icon_search_area,
  'search-circle': icon_search_circle,
  'search-focus': icon_search_focus,
  'search-list-01': icon_search_list_01,
  'search-list-02': icon_search_list_02,
  'search-minus': icon_search_minus,
  'search-remove': icon_search_remove,
  'search-square': icon_search_square,
  'search-visual': icon_search_visual,
  searching: icon_searching,
  'zoom-in-area': icon_zoom_in_area,
  'zoom-out-area': icon_zoom_out_area,
} as const;
