// AUTO-GENERATED by scripts/import-icons.mjs — do not edit by hand.
// Re-run `node scripts/import-icons.mjs` after adding raw exports to
// scripts/icon-raw/shapes/ to regenerate this category's registry.
import icon_circle from '@/assets/icons/shapes/circle.svg?raw';
import icon_diamond from '@/assets/icons/shapes/diamond.svg?raw';
import icon_geometric_shapes_01 from '@/assets/icons/shapes/geometric-shapes-01.svg?raw';
import icon_geometric_shapes_02 from '@/assets/icons/shapes/geometric-shapes-02.svg?raw';
import icon_hexagon from '@/assets/icons/shapes/hexagon.svg?raw';
import icon_oval from '@/assets/icons/shapes/oval.svg?raw';
import icon_pentagon from '@/assets/icons/shapes/pentagon.svg?raw';
import icon_polygon from '@/assets/icons/shapes/polygon.svg?raw';
import icon_rectangular from '@/assets/icons/shapes/rectangular.svg?raw';
import icon_rhombus from '@/assets/icons/shapes/rhombus.svg?raw';
import icon_seal from '@/assets/icons/shapes/seal.svg?raw';
import icon_shapes from '@/assets/icons/shapes/shapes.svg?raw';
import icon_spirals from '@/assets/icons/shapes/spirals.svg?raw';
import icon_square from '@/assets/icons/shapes/square.svg?raw';
import icon_triangle from '@/assets/icons/shapes/triangle.svg?raw';

export const shapesIcons = {
  circle: icon_circle,
  diamond: icon_diamond,
  'geometric-shapes-01': icon_geometric_shapes_01,
  'geometric-shapes-02': icon_geometric_shapes_02,
  hexagon: icon_hexagon,
  oval: icon_oval,
  pentagon: icon_pentagon,
  polygon: icon_polygon,
  rectangular: icon_rectangular,
  rhombus: icon_rhombus,
  seal: icon_seal,
  shapes: icon_shapes,
  spirals: icon_spirals,
  square: icon_square,
  triangle: icon_triangle,
} as const;
